### ISSUE TITLE
[It's not the] Same as in #71

### ISSUE THREAD

**Issue by shahin365** [dayanch96/YTLite#100]
Same as in #71

_Originally posted by @dayanch96 in https://github.com/dayanch96/YTLite/issues/98#issuecomment-2088442493_

**Comment by shahin365** [comment]
> ```
>           Same as in #71
> ```
> 
> _Originally posted by @dayanch96 in [#98 (comment)](https://github.com/dayanch96/YTLite/issues/98#issuecomment-2088442493)_

I have tried disabling the 'Hide Shorts' option to fix the blank space problem, but it didn't work in my case. Some users on GitHub & Reddit have also reported facing the same issue in the past few weeks. It seems that the only solution that works for everyone is to disable the ad-blocker, but that defeats the purpose of using YTLite. The root cause of this bug is the ad-blocker, not the 'Hide Shorts' feature.

**Comment by dayanch96** [comment]
Fixed
