### ISSUE TITLE
Shorts UI elements hiding options don't work properly

### ISSUE THREAD

**Issue by Uwe5000** [dayanch96/YTLite#101]
iPhone XR 
iOS 16.3 Dopamine

Some UI element hiding options for the Shorts tab don't work properly.
Hiding the dislike button doesn't actually hide it for example.

♥️

**Comment by dayanch96** [comment]
Removed as now we have Pinch gesture to hide all elements

**Comment by Uwe5000** [comment]
Got the new ver but still same issues with shorts
The pinch to fullscreen feature works perfect though
♥️

**Comment by dayanch96** [comment]
As I said, removed options to hide elements. Thats why😅

**Comment by Uwe5000** [comment]
Aaahhhh ok
Thank you so much for that great work 

But it's a little confusing because the options are still in the settings table 

♥️

**Comment by dayanch96** [comment]
are you sure about that? make sure it installed properly
![IMG_1657](https://github.com/dayanch96/YTLite/assets/38832025/29b5a602-1fce-4d8b-b1b7-f130113a380f)

**Comment by Uwe5000** [comment]
Well they are actually gone 😅

Sorry I,m little high 

Great that you keep on working on the project 

It's just the best one imo

♥️

**Comment by dayanch96** [comment]
Thanks. Have a good one
