### ISSUE TITLE
Blank screen issue still persist on v4.0 + Export preferences crash

### ISSUE THREAD

**Issue by LaxusiC** [dayanch96/YTLite#105]
![86CA43E3-3897-4921-BC06-3378D97C8A67](https://github.com/dayanch96/YTLite/assets/9650215/61f0b6fa-e150-46ce-9be7-1efd0712f082)

Crash logs when trying to use export preferences
https://drive.google.com/file/d/1zn0b_ZifaGOhKSokJpqFnZ-E2b3wKUdL/view?usp=drivesdk

**Comment by dayanch96** [comment]
Need more info

**Comment by LaxusiC** [comment]
> Need more info

I updated crash logs when export preferences crash

Not sure how to give you info about blank screen issue. I dont have it on iPhone, just iPad

**Comment by dayanch96** [comment]
> > Need more info
> 
> I updated crash logs when export preferences crash
> 
> Not sure how to give you info about blank screen issue. I dont have it on iPhone, just iPad

Thats enough for now. Thanks

**Comment by dayanch96** [comment]
@LaxusiC turns out that YouTube works bit different in landscape mode on iPad layout. For now, can only suggest to use in portrait mode on Subs tab - I'll try to fix it for the next update

**Comment by abheizthe** [comment]
> @LaxusiC turns out that YouTube works bit different in landscape mode on iPad layout. For now, can only suggest to use in portrait mode - I'll try to fix it for the next update

@dayanch96 Sorry OOT but, would you mind to open a discussion in the releases section? Maybe just before creating an issues form

Anyway, thank you for this update
The first i think is; my account got banned because i can't play any videos LOL

**Comment by Macleykun** [comment]
> Crash logs when trying to use export preferences https://drive.google.com/file/d/1zn0b_ZifaGOhKSokJpqFnZ-E2b3wKUdL/view?usp=drivesdk

I too have that issue with the preference
Did you sideload it (ipa) or use tweak injection (jailbreak/deb)? And do you only use YTLite?

**Comment by LaxusiC** [comment]
> > Crash logs when trying to use export preferences https://drive.google.com/file/d/1zn0b_ZifaGOhKSokJpqFnZ-E2b3wKUdL/view?usp=drivesdk
> 
> I too have that issue with the preference Did you sideload it (ipa) or use tweak injection (jailbreak/deb)? And do you only use YTLite?

Both having issue
