### ISSUE TITLE
Localization is not displayed correctly

### ISSUE THREAD

**Issue by Balackburn** [dayanch96/YTLite#106]
For 4.0, sideloaded, I use FRENCH as my system language.

![Capture d’écran   2024-06-01 à 17 07 53](https://github.com/dayanch96/YTLite/assets/93828569/762ef806-2b96-461e-8191-fe4855d3fe0e)

**Comment by dayanch96** [comment]
Localizations not updated yet. I’ll post it soon here or at crowdin

**Comment by Balackburn** [comment]
@dayanch96 👍
