### ISSUE TITLE
[Bug] Hiding Shorts Doesn’t Work Properly

### ISSUE THREAD

**Issue by ev0tto** [dayanch96/YTLite#110]
As the title says, hiding shorts doesn’t work properly. It results in blank spaces as before. However, interestingly, if I switch accounts, the blank spaces disappear cleanly. 
I’m a non-jailbroken user, and I sideload the .ipa file.

- Video
https://github.com/dayanch96/YTLite/assets/80548883/3579da16-0954-4986-8595-0eddfdd942eb

- Settings file (I just changed file name, please remove .zip)
[com.dvntm.ytlite.plist.zip](https://github.com/user-attachments/files/15527099/com.dvntm.ytlite.plist.zip)

**Comment by dayanch96** [comment]
Thanks for the issue. I’ll close it as we have #105 already

**Comment by ev0tto** [comment]
Is the issue# 105 related to the blank space in the Home tab (without hiding Shorts) and is it on an iPad? However, would you consider it the same category?

**Comment by dayanch96** [comment]
yess its same

**Comment by ev0tto** [comment]
@dayanch96 

This might be a different topic, but it's about hiding Shorts, so I'll report it here for now.

On the search results page, only the title of the Shorts remains.
It seems to disappear when the language is set to English.
I encountered this issue by setting the app's language to Japanese.

![image](https://i.postimg.cc/GpMxNjpG/IMG-3349.jpg)
