### ISSUE TITLE
Некорректное действие опции "Скрыть "Трансляция"" 

### ISSUE THREAD

**Issue by vitalik2187836** [dayanch96/YTLite#114]
Кнопка находится в разделе с навбаром, соответственно предполагается, что кнопка будет скрыта только оттуда. Но по факту кнопка скрывается и из плеера. 
Наверное логичнее сделать так, чтобы эта опция скрывала только кнопку в навбаре, а в раздел "Настройки плеера" добавить еще одну опцию для скрытия кнопки трансляции, если она кому-то не нужна 
Ps: версия 4 - топ, но я не нашел, есть ли где-то менюшка со скачанными видео

**Comment by dayanch96** [comment]
спасибо. но ни первое, ни второе менять не планируется. твик и так становится громоздким
