### ISSUE TITLE
[Feature Request] Play next in queue

### ISSUE THREAD

**Issue by NBA2K1** [dayanch96/YTLite#115]
I opened an [issue](https://github.com/YTLitePlus/YTLitePlus/issues/162#issue-2331848012) at the YTLitePlus repo and was forwarded here by @Balackburn 

Is it possible to add the "Play next in queue" premium feature from the original app?

**Comment by dayanch96** [comment]
Hey. Of you’re asking for adding this option to videos context menu, you can bring it back in tweak settings (Interface section). Turn off the option called ‘remove play next in queue’.

Keep in mind that it still requires youtube premium subscription.

**Comment by NBA2K1** [comment]
No, I already had that option turned off. What I am asking for is, for this feature to be added so that it doesn’t require a Premium subscription, like how the download feature or PiP feature was added and it can be used without Premium.

**Comment by dayanch96** [comment]
Its not the same PiP and downloading features as in premium.

And sorry - I don’t have any plans to implement it in the near future
