### ISSUE TITLE
[request] Add option to hide "search by image" element

### ISSUE THREAD

**Issue by ev0tto** [dayanch96/YTLite#118]
When I search, an element titled "画像で検索"(Search by image in English?) appears in Japanese. As the name suggests, this element suggests websites on the search page, just like Google Search, if what you searched for also exists on the internet.
So far, I have discovered this element when searching for the string "pokemon snap." I did not find it when searching for "Pokémon Snap." I am not sure if this difference is due to the account or the search term.
Anyway, I would be happy if I could hide this element.
Thank you in advance.

![image](https://i.postimg.cc/MGkWSp7d/lz2d5z.jpg)

**Comment by dayanch96** [comment]
Sorry, not planned
