### ISSUE TITLE
Possible to bring back Old hold to seek feature

### ISSUE THREAD

**Issue by FrostyBits77** [dayanch96/YTLite#120]
### Describe the feature request

```yaml
Is it possible possible to add back hold to seek feature? Replace hold to fastward with awesome old hold to seek feature.
```

### Post Requisites

- [x] I have checked that a similar feature request has not been reported before.
- [X] Verified the relevance of the project and the version you are using.
- [X] Provided a detailed description of the request and have filled in all required fields.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.
- [X] By submitting this request, **I confirm that I have filled in all the necessary fields and complied with the guidelines. Failure to comply may result in the request being closed without discussion, and repeated violations may lead to restrict account from further participation.**

**Comment by dayanch96** [comment]
Set hold to speed option to Disabled and restart the app

**Comment by FrostyBits77** [comment]
> Set hold to speed option to Disabled and restart the app

Thanks for fast reply but this doesn’t work. This just disable hold to speed and doesn’t give old feature back.

**Comment by dayanch96** [comment]
then try swipe up scrubber, irrc it was moved there

**Comment by FrostyBits77** [comment]
Old youtbe had a feature where I could tap hold anywhere on screen to move scrubber. Hope there’s a way to bring this feature back.

**Comment by dayanch96** [comment]
I know. And no, I can’t bring everything that each user wants. Sorry for that, but you might want to use older YT versions for that

**Comment by bhackel** [comment]
If you have YTABConfig, you can disable this flag: speedMasterArm2FastForwardWithoutSeekBySliding
Not sure if it still works but it definitely used to
