### ISSUE TITLE
Infinite buffering at 0:10 mark

### ISSUE THREAD

**Issue by vghost01** [dayanch96/YTLite#125]
### Describe the bug

```yaml
There's a bug that's prevalent on all Youtube tweaks that remove video ads, including YTLite:

Randomly, when I click a video, it will start infinitely buffering at exaclty the 0:10 mark. And if I exit that video and try to open other videos, they will not load at all. 

If I wait around 1 minute on the app while doing nothing and try again, videos will load normally again. Then after a certain amount of time/videos, the infinite buffering at 0:10 will happen on a video again, and rinse and repeat.

I have been able to reproduce this exact scenario at least 50 times by now, but cannot find a solution. Apparently, a similar issue has happened on ReVanced Youtube on Android, but the issue has been fixed there.

I am using iOS 15.6, Youtube ver 19.24.2, YTLite ver 4.0.1. Have tested on multiple versions of Youtube, but the same issue exists on them all.
```

### Steps to reproduce

```yaml
Open any video, and it may start infinitely buffering at the 0:10 mark. May take multiple attemps before it happens.
```

### Post Requisites

- [X] I have checked that a similar issue has not been reported before.
- [X] Verified the relevance of the project and the version you are using.
- [X] Provided a detailed description of the problem and have filled in all required fields.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.
- [X] By submitting this issue, **I confirm that I have filled in all the necessary fields and complied with the guidelines. Failure to comply may result in the issue being closed without discussion, and repeated violations may lead to restrict account from further participation.**

**Comment by dayanch96** [comment]
Hey, thanks. Im aware of that issue. It happens when you have new type of ads, which i dont have yet due to regional differences. Will take a look when it "comes to me"

**Comment by vghost01** [comment]
For now, I've fixed it by using a VPN and setting it to a different country. But a native fix would definitely be much better.
