### ISSUE TITLE
Allow speeding up playback of livestreams to minimize delay

### ISSUE THREAD

**Issue by Void48** [dayanch96/YTLite#126]
### Describe the feature request

```yaml
It's very useful on web YouTube because it helps minimize the shitty delays that happen when you watch a livestream. An even better feature would be if it could catch up to the latest point in the livestream because speeding up the player sometimes causes lag, leaving you a second or a few seconds behind. On the web I use an extension called Previews (For TTV & YT), which has Playback Speed Controls. It will speed up until it catches up to the latest point of the livestream without lagging.
```

### Post Requisites

- [X] I have checked that a similar feature request has not been reported before.
- [X] Verified the relevance of the project and the version you are using.
- [X] Provided a detailed description of the request and have filled in all required fields.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.
- [X] By submitting this request, **I confirm that I have filled in all the necessary fields and complied with the guidelines. Failure to comply may result in the request being closed without discussion, and repeated violations may lead to restrict account from further participation.**

**Comment by dayanch96** [comment]
Just tap to livestream text and it will mve you to the latest buffered point. There no magic that can help you minimize your ping

**Comment by dayanch96** [comment]
I don’t have time nor desire for that. I wont make this feature anyway, sorry
