### ISSUE TITLE
Plz add some kind of Download manager where downloaded Videos/Audio can stay with in app & Volume gesture

### ISSUE THREAD

**Issue by Blockr22** [dayanch96/YTLite#128]
### Describe the feature request

```yaml
Volume gesture- change volume when sliding at the top of the screen going left & right like that un uYouEnhanced
Download manager like uYou where downloaded videos/Audio’s go after being downloaded. So that we don’t have to leave the app to find & play files. Now it’s just little bit annoying that it save videos in files app.
Other than that i think it works great & fast downloading is great. I would switch to this app from uYouEnhanced if it gets these features
```

### Post Requisites

- [X] I have checked that a similar feature request has not been reported before.
- [X] Verified the relevance of the project and the version you are using.
- [X] Provided a detailed description of the request and have filled in all required fields.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.
- [X] By submitting this request, **I confirm that I have filled in all the necessary fields and complied with the guidelines. Failure to comply may result in the request being closed without discussion, and repeated violations may lead to restrict account from further participation.**

**Comment by dayanch96** [comment]
Sorry, but since the project is not monetized and has very little income, new features are added solely at my discretion. Currently, I do not plan to add anything new, only to fix bugs. Thank you for understanding
