### ISSUE TITLE
Proposal to Change the Contributor Section

### ISSUE THREAD

**Issue by SKEIDs** [dayanch96/YTLite#130]
### Describe the feature request

```yaml
Currently, my account is listed, but Mr.ichitaso has made more superior localization changes and corrections. 
Therefore, I think it should change the Contributor section to reflect ichitaso's contributions.

https://github.com/dayanch96/YTLite/blob/54de3baf79b2ab6cf240d9b08690d2bda4444d1c/Settings.x#L545
```

### Post Requisites

- [X] I have checked that a similar feature request has not been reported before.
- [X] Verified the relevance of the project and the version you are using.
- [X] Provided a detailed description of the request and have filled in all required fields.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.
- [X] By submitting this request, **I confirm that I have filled in all the necessary fields and complied with the guidelines. Failure to comply may result in the request being closed without discussion, and repeated violations may lead to restrict account from further participation.**

**Comment by dayanch96** [comment]
Hey, thanks. As it been told, source code outdated. I've already added them to the contributors list on my local repo

**Comment by dayanch96** [comment]
I can keep both, but up to you
