### ISSUE TITLE
Sync the latest locations in the repo

### ISSUE THREAD

**Issue by Balackburn** [dayanch96/YTLite#132]
### Describe the feature request

```yaml
I'd like to translate all the missing localizations into French, if you could sync the localizations of the latest YTLite 5.0 beta in the repo so that we can help translate them it would be great.

Thank you for your amazing work.
```

### Post Requisites

- [X] I have checked that a similar feature request has not been reported before.
- [X] Verified the relevance of the project and the version you are using.
- [X] Provided a detailed description of the request and have filled in all required fields.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.
- [X] By submitting this request, **I confirm that I have filled in all the necessary fields and complied with the guidelines. Failure to comply may result in the request being closed without discussion, and repeated violations may lead to restrict account from further participation.**

**Comment by dayanch96** [comment]
Hey. Done: https://github.com/dayanch96/YTLite/blob/main/layout/Library/Application%20Support/YTLite.bundle/fr.lproj/Localizable.strings
