### ISSUE TITLE
Channel watermark reappears when tapping the controls and dismissing ghem

### ISSUE THREAD

**Issue by reticivis-net** [dayanch96/YTLite#136]
### Describe the bug

When opening a video the watermark is gone, but if you tap twice it reappears

This exact issue happened with uyouplus and it was fixed there. https://github.com/qnblackcat/uYouPlus/issues/1292

### Steps to reproduce

- Turn on hide channel watermark
- open a video
- fullscreen it
- tap to show controls
- tap again to hide them

### Post Requisites

- [X] I have checked that a similar issue has not been reported before.
- [X] Verified the relevance of the project and the version you are using.
- [X] Provided a detailed description of the problem and have filled in all required fields.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.
- [X] By submitting this issue, **I confirm that I have filled in all the necessary fields and complied with the guidelines. Failure to comply may result in the issue being closed without discussion, and repeated violations may lead to restrict account from further participation.**

**Comment by reticivis-net** [comment]
???

**Comment by reticivis-net** [comment]
Oh oops

**Comment by dayanch96** [comment]
Now I'll take a look, but rest really not planned. Thank you for your time

**Comment by dayanch96** [comment]
By the way, can you give me any link with videos that contain watermrks?

**Comment by reticivis-net** [comment]
https://youtu.be/KK3mS4bQ5JM

by the way, assuming you’re using the same code as uYouPlus, a fix already exists https://github.com/qnblackcat/uYouPlus/pull/1296

**Comment by dayanch96** [comment]
no, not the same. thank you though

**Comment by dayanch96** [comment]
I don’t have wm. Which tweak exactly you’re using?

**Comment by reticivis-net** [comment]
Even after showing and hiding the controls in fullscreen?

I’m using a custom YTLitePlus build at YouTube 19.30.2 and commit https://github.com/YTLitePlus/YTLitePlus/commit/d731dbddeca24a6e70764fb8433f75088e5cb88c and I believe YTLite itself is at 4.0.1

I can send you the ipa itself but I don’t think I’m allowed to through GitHub

**Comment by dayanch96** [comment]
I can’t nor want to dive headlong into the problems of 3rd-party mods. I can only suggest trying [YTLite IPA](https://t.me/dvntms/71), not YTLitePlus, or submitting issue in YTLitePlus repo

**Comment by reticivis-net** [comment]
Ah yeah I can’t reproduce it with the linked ipa. My bad, I assumed it was a ytlite issue. I’ll raise an issue on the ytliteplus repo. Thanks for looking into it!

**Comment by dayanch96** [comment]
Glad we found out. So I’m closing the issue and removing link to avoid any problems. Thanks
