### ISSUE TITLE
Building YTLite on GitHub

### ISSUE THREAD

**Issue by Skawtnyc** [dayanch96/YTLite#153]
### Describe the feature request

```yaml
Would it be possible for someone to add a workflow file to compile YTLite on GitHub itself? YTLite+ has one, but there’s no clear method on how to specifically build YTLite. Using the buildapp.yml for YTLite+ doesn’t work because it’s looking for things that don’t exist.
```

### Post Requisites

- [X] I have checked that a similar feature request has not been reported before.
- [X] Verified the relevance of the project and the version you are using.
- [X] Provided a detailed description of the request and have filled in all required fields.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.
- [X] By submitting this request, **I confirm that I have filled in all the necessary fields and complied with the guidelines. Failure to comply may result in the request being closed without discussion, and repeated violations may lead to restrict account from further participation.**

**Comment by dayanch96** [comment]
hey. sure. i’ll add one with the 5.0 release

**Comment by Skawtnyc** [comment]
> hey. sure. i’ll add one with the 5.0 release

Looking forward to it. I like what you’ve done with 5.0beta so far, having seen a sample of it on YTLite+.
