### ISSUE TITLE
Opus audio codec is being used automatically sideloaded

### ISSUE THREAD

**Issue by gototheskinny** [dayanch96/YTLite#157]
### Describe the bug

```yaml
Device : 
iPhone 14 pro 
ios 17.3.1 
esign 

I'm concerned that Apple may not allow hardware acceleration for the Opus codec across all applications. While they restrict hardware acceleration for AV1 and VP9 codecs (with Google having a special entitlement), this could mean that Opus audio files are processed by the CPU for sideloaded apps. This would result in higher power consumption and reduced battery life. Previous versions used the AAC codec, which benefits from nearly 100% hardware acceleration, even for sideloaded apps. This change could introduce inefficiencies. Could you please investigate this potential issue?
```

### Steps to reproduce

```yaml
1 open the stats for nerds in the settings
2 open a recent video 
3 you'll see the opus codec in the audio section of the stats
```

### Post Requisites

- [X] I have checked that a similar issue has not been reported before.
- [X] Verified the relevance of the project and the version you are using.
- [X] Provided a detailed description of the problem and have filled in all required fields.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.
- [X] By submitting this issue, **I confirm that I have filled in all the necessary fields and complied with the guidelines. Failure to comply may result in the issue being closed without discussion, and repeated violations may lead to restrict account from further participation.**

**Comment by dayanch96** [comment]
Ne alakası var ki YTLite ile? Entitlements sadece vp9 için lazım. av1’in ona hiç ihtiyacı yok, hem de sadece 15 pro modellerine uygun (14 Pro’dan emin değilim). Maalesef, benim ne 14 pro, ne de 15 pro cihazım var :D

**Comment by gototheskinny** [comment]
> Ne alakası var ki YTLite ile? Entitlements sadece vp9 için lazım. av1’in ona hiç ihtiyacı yok, hem de sadece 15 pro modellerine uygun (14 Pro’dan emin değilim). Maalesef, benim ne 14 pro, ne de 15 pro cihazım var :D

Opus cpuyu kullanmıyorsa sorun yok vp9 falan cpunun nanasini dikiyor opusta gereksiz cpuyu kullanıpta gereksiz ısınma ve güç kullanmasın. Eğer hw acceleration varsa gerek yok bişey yapmana ama diğer tweakler ve bir önceki  ytliteplus sürümü aac kullanıyordu

**Comment by dayanch96** [comment]
> > Ne alakası var ki YTLite ile? Entitlements sadece vp9 için lazım. av1’in ona hiç ihtiyacı yok, hem de sadece 15 pro modellerine uygun (14 Pro’dan emin değilim). Maalesef, benim ne 14 pro, ne de 15 pro cihazım var :D
> 
> Opus cpuyu kullanmıyorsa sorun yok vp9 falan cpunun nanasini dikiyor opusta gereksiz cpuyu kullanıpta gereksiz ısınma ve güç kullanmasın. Eğer hw acceleration varsa gerek yok bişey yapmana ama diğer tweakler ve bir önceki ytliteplus sürümü aac kullanıyordu

vp9 belirli bir teamID’e veriliyor, örneğin google’ın apple hesabına. sen uygulamayı resign edince, senin sertifikadaki teamID’i kullanıyor, bununla da vp9 entitlements’in olmamış oluyor. opusun ona hiç ihtiyacı yok, sen mp4 üzerinden o kodek’i kullanıyorsun

**Comment by gototheskinny** [comment]
> > > Ne alakası var ki YTLite ile? Entitlements sadece vp9 için lazım. av1’in ona hiç ihtiyacı yok, hem de sadece 15 pro modellerine uygun (14 Pro’dan emin değilim). Maalesef, benim ne 14 pro, ne de 15 pro cihazım var :D
> 
> > 
> 
> > Opus cpuyu kullanmıyorsa sorun yok vp9 falan cpunun nanasini dikiyor opusta gereksiz cpuyu kullanıpta gereksiz ısınma ve güç kullanmasın. Eğer hw acceleration varsa gerek yok bişey yapmana ama diğer tweakler ve bir önceki ytliteplus sürümü aac kullanıyordu
> 
> 
> 
> vp9 belirli bir teamID’e veriliyor, örneğin google’ın apple hesabına. sen uygulamayı resign edince, senin sertifikadaki teamID’i kullanıyor, bununla da vp9 entitlements’in olmamış oluyor. opusun ona hiç ihtiyacı yok, sen mp4 üzerinden o kodek’i kullanıyorsun

Google exclusive değilse sorun yok o zaman ama bence pili daha çok kullanır gibime geliyor aac çok daha fazla geniş desteğe sahip özellikle eski iphonelar için ama orijinal youtube da bunu en azından  benim bildiğim kadarıyla yeni iphonelar için kullanıyor eskilerini bilemiyorum. 


Neyse bişey sormam lazım sponsorblock un bölüm gönderme düğmesi oynatıcıda çıkmıyor yenisi çok iyi olmuş ama bölüm gönderme özelliği olsaydı çok iyi olurdu benimmi goxumden kaçmış acaba?

**Comment by dayanch96** [comment]
google’un kullandığı av1 biraz değişik, bildiğin avc değil

bölüm gönderme özelliği yok şimdilik, gelecekte eklerim

**Comment by dayanch96** [comment]
Issue’yi kapatıyorum başka sorun yoksa. Eğer varsa tekrar açabilirsin

**Comment by gototheskinny** [comment]
> Issue’yi kapatıyorum başka sorun yoksa. Eğer varsa tekrar açabilirsin

Yok başka sorum. Gerçekten tweaki Google yapsa bu kadar yapardı çok çok iyi olmuş eline sağlık. Türkçe'de Bir iki hata var onları düzeltip Req açarım istersen eklersin sana kalmış. sponsorblock ekleme öz. haricinde Bi eksik şimdilik yok gibi gerçekten tebrikler!

**Comment by dayanch96** [comment]
sevinirim kankam, gönül rahatlığıyla pr açabilirsin. sanırım premium üyeler için 'skip to highlight' gibi bir şeyler yapıyorlardı.
