### ISSUE TITLE
[Feature request] More hiding options

### ISSUE THREAD

**Issue by Lilypad64** [dayanch96/YTLite#16]
I would like to see options to hide related videos at the bottom of the comment section and search suggestions (if it is possible).

**Comment by dayanch96** [comment]
> related videos at the bottom of the comment section

Can I have screenshot?

**Comment by dayanch96** [comment]
I’ll take a look later today. Thanks for the screenshots

**Comment by dayanch96** [comment]
@Lilypad64 Like this?
![2F1B762E-AFAF-4560-BBB3-FB306A3BB4B5](https://github.com/dayanch96/YTLite/assets/38832025/b392de01-e8a1-4009-b4fe-db43dfa18609)
![46F7303A-C634-4477-B0F1-5B6C2E4159AD](https://github.com/dayanch96/YTLite/assets/38832025/763582da-a059-4de0-adcd-5a7d36e5fa48)

**Comment by dayanch96** [comment]
OK

**Comment by dayanch96** [comment]
Here you go: https://github.com/dayanch96/YTLite/releases/tag/v2.3

https://github.com/dayanch96/YTLite/commit/5862a73ac9dddd5867b141e769a5b2f88a674ef8
