### ISSUE TITLE
[Request] hide “download” “thanks” “clip” “save” buttons under video player

### ISSUE THREAD

**Issue by systox** [dayanch96/YTLite#161]
### Describe the feature request

```yaml
Great tweak, ty.

Can we hide the Download, thanks, clip, and save buttons under the video player? Annotated below.
```

<img width="1376" alt="image" src="https://github.com/user-attachments/assets/aaf1f42d-ce37-4be7-84f2-326203de0ff8">

### Post Requisites

- [X] I have checked that a similar feature request has not been reported before.
- [X] Verified the relevance of the project and the version you are using.
- [X] Provided a detailed description of the request and have filled in all required fields.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.
- [X] By submitting this request, **I confirm that I have filled in all the necessary fields and complied with the guidelines. Failure to comply may result in the request being closed without discussion, and repeated violations may lead to restrict account from further participation.**

**Comment by dayanch96** [comment]
Completed here: https://github.com/dayanch96/YTLite/releases/tag/v5.1
