### ISSUE TITLE
[Request] Hide “join” and “notifications” buttons under video player

### ISSUE THREAD

**Issue by systox** [dayanch96/YTLite#162]
### Describe the feature request

```yaml
Like my other suggestion but on another line under the video player. Can we hide the join and notifications button? See screenshot. 

Thank you.
```
<img width="1162" alt="image" src="https://github.com/user-attachments/assets/369a1203-4daa-4a85-b56e-e3bdbca19ba7">

### Post Requisites

- [X] I have checked that a similar feature request has not been reported before.
- [X] Verified the relevance of the project and the version you are using.
- [X] Provided a detailed description of the request and have filled in all required fields.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.
- [X] By submitting this request, **I confirm that I have filled in all the necessary fields and complied with the guidelines. Failure to comply may result in the request being closed without discussion, and repeated violations may lead to restrict account from further participation.**

**Comment by dayanch96** [comment]
Completed here: https://github.com/dayanch96/YTLite/releases/tag/v5.1
