### ISSUE TITLE
[Bug] Shorts are intermittently scrolling 2 at a time.

### ISSUE THREAD

**Issue by systox** [dayanch96/YTLite#163]
### Describe the bug

```yaml
On iPad and iPhone, scrolling shorts manually skips over videos randomly for some reason. See attached screen recording.
```

https://github.com/user-attachments/assets/ed7ca247-ad89-4a66-9bb8-0f0e9a3916c2

### Steps to reproduce

```yaml
I have the shorts, “scroll to next” setting enabled. Not sure if that plays into it.
```

### Post Requisites

- [X] I have checked that a similar issue has not been reported before.
- [X] Verified the relevance of the project and the version you are using.
- [X] Provided a detailed description of the problem and have filled in all required fields.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.
- [X] By submitting this issue, **I confirm that I have filled in all the necessary fields and complied with the guidelines. Failure to comply may result in the issue being closed without discussion, and repeated violations may lead to restrict account from further participation.**

**Comment by dayanch96** [comment]
Fixed in 5.0.2
