### ISSUE TITLE
[Request] Icon on video player for YT “Lock Screen” button.

### ISSUE THREAD

**Issue by systox** [dayanch96/YTLite#165]
### Describe the feature request

```yaml
YouTube has a settings feature called “Lock Screen” that can be toggled and prevents accidental screen touches. This is useful for when the screen gets wet, etc. It’s a pain to activate tho since it’s under the video player settings menu (screen shot). Could we add an icon on the video player screen to quickly toggle this feature on?

Thanks for considering.
```

<img width="1376" alt="image" src="https://github.com/user-attachments/assets/486071e4-d25f-4136-aded-27ecba291f90">

### Post Requisites

- [X] I have checked that a similar feature request has not been reported before.
- [X] Verified the relevance of the project and the version you are using.
- [X] Provided a detailed description of the request and have filled in all required fields.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.
- [X] By submitting this request, **I confirm that I have filled in all the necessary fields and complied with the guidelines. Failure to comply may result in the request being closed without discussion, and repeated violations may lead to restrict account from further participation.**

**Comment by dayanch96** [comment]
Sure. I will take a look

**Comment by systox** [comment]
Thanks Dayanch, no pressure or rush.

**Comment by dayanch96** [comment]
Completed here: https://github.com/dayanch96/YTLite/releases/tag/v5.1
