### ISSUE TITLE
Preffered Captions: Always show (auto-generated) captions in original language

### ISSUE THREAD

**Issue by craftgeil** [dayanch96/YTLite#167]
### Describe the feature request

```yaml
With the help of an article from google I learned that subtitles can always be displayed (even on iOS/iPadOS) without manually enabling them (Picture 1). However this only works with videos wich have proper subtitles, so any videos with auto-generated ones, I still have to enable them manually.

Using the newly released "Preffered-captions" feature to select one fixed language does not work for me, because I want e.g. german videos with german captions and english videos with english captions.

Is it possible to add a feature, which always shows captions even when they are auto-generated like on desktop (Picture 2)?
```
Article from google to always enable subtitles on iOS / iPadOS:
![IMG_0457](https://github.com/user-attachments/assets/a0977741-b740-4dab-bf7a-6bcb836b013f)

Option on the desktop version:
![IMG_0458](https://github.com/user-attachments/assets/d6e59f23-d41a-4577-b713-43caea8729e7)

How it currently is when opening videos on iPhone / iPad (auto-generated ones are not picked)
![ipad(1)](https://github.com/user-attachments/assets/ea13bf6c-4465-4909-a9f3-f24401d5194a)

How it is on PC (auto-generated ones are also enabled automatically)
![pc](https://github.com/user-attachments/assets/59c0b270-c402-4ca8-89b8-7424625e1d6d)

### Post Requisites

- [X] I have checked that a similar feature request has not been reported before.
- [X] Verified the relevance of the project and the version you are using.
- [X] Provided a detailed description of the request and have filled in all required fields.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.
- [X] By submitting this request, **I confirm that I have filled in all the necessary fields and complied with the guidelines. Failure to comply may result in the request being closed without discussion, and repeated violations may lead to restrict account from further participation.**

**Comment by dayanch96** [comment]
I may add option for subtitles that selects the original language, as I did with the audio-track

**Comment by dayanch96** [comment]
Added in 5.0.2. Don't forget to enable "Auto-generated captions" option to be able to select auto-generated/translated captions
