### ISSUE TITLE
Crash on Shorts Default Quality

### ISSUE THREAD

**Issue by CiroHoodLove** [dayanch96/YTLite#172]
### Describe the bug

```yaml
Okey so i got 2 points and one isn’t a bug but an oversight i might say

the shorts crash the app when you watch more than 2 or 3 it varies from time to time sometimes 1 (like in the attached video ) sometimes even 4
Also the oversight is , when you remove the library from the tab bar , you won’t be able to access the settings again , i had to reinstall youtube again to have it show up again

the crashing was caused by me setting specific default quality for shorts , when i returned it to the default it stopped the crashing , i already opened an issue you can check it on this link : https://github.com/YTLitePlus/YTLitePlus/issues/401
```

### Steps to reproduce

```yaml
Open Youtube

Click on Shorts

Scroll and it will crash

Open Youtube

Navigate to Settings > Youtube Plus > Tab Bar

Remove Library
```

### Crashlog

**My YouTubePlus Settings** 

https://easyupload.io/5p86ve

**My Crash Logs**

https://easyupload.io/m/0cb8oh

P.S : some crash logs are different because they happened in different scenarios , like opening shorts from a video already playing crashed it directly , 

### Post Requisites

- [X] I have checked that a similar issue has not been reported before.
- [X] Verified the relevance of the project and the version you are using.
- [X] Provided a detailed description of the problem and have filled in all required fields.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.
- [X] By submitting this issue, **I confirm that I have filled in all the necessary fields and complied with the guidelines. Failure to comply may result in the issue being closed without discussion, and repeated violations may lead to restrict account from further participation.**

**Comment by dayanch96** [comment]
Fixed in new update

**Comment by dayanch96** [comment]
UPD: You can add/remove "You" tab by long pressing the first tab button from the tab bar
