### ISSUE TITLE
DontEatMyContent 

### ISSUE THREAD

**Issue by Ketarmin** [dayanch96/YTLite#179]
### Describe the feature request

```yaml
Can you please add option like the tweak DontEatMyContent ? 

There are few videos where it’s really handy to have this tweak
```

### Post Requisites

- [X] I have checked that a similar feature request has not been reported before.
- [X] Verified the relevance of the project and the version you are using.
- [X] Provided a detailed description of the request and have filled in all required fields.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.
- [X] By submitting this request, **I confirm that I have filled in all the necessary fields and complied with the guidelines. Failure to comply may result in the request being closed without discussion, and repeated violations may lead to restrict account from further participation.**

**Comment by Ketarmin** [comment]
![IMG_5918](https://github.com/user-attachments/assets/6a76d846-cf17-4c72-84e6-657fc3d27daf)

**Comment by dayanch96** [comment]
Hey, why not inject the tweak manually into the IPA?

**Comment by Ketarmin** [comment]
> Hey, why not inject the tweak manually into the IPA?

Of course, but I heard about some people that tried to inject tweaks which then triggered a pup-up that’s warning us about conflicting tweaks/ options which may already exist.

So that’s why I think I should ask you first if it would be possible to implement it

**Comment by dayanch96** [comment]
No, nothing similar exists and it has no conflicts with the YTPlus. Feel free to inject it
