### ISSUE TITLE
[Request] Add option to disable subtitles on feed

### ISSUE THREAD

**Issue by ev0tto** [dayanch96/YTLite#181]
### Describe the feature request

```yaml
I want to disable the automatic captions that turn on when video previews play on the Home or Subscriptions tabs.
```

<details>
<summary> Screenshot </summary>

![image](https://github.com/user-attachments/assets/c55849be-1d8e-4ce7-b73d-6c7c3d2c1b1b)

</details>

### Post Requisites

- [X] I have checked that a similar feature request has not been reported before.
- [X] Verified the relevance of the project and the version you are using.
- [X] Provided a detailed description of the request and have filled in all required fields.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.
- [X] By submitting this request, **I confirm that I have filled in all the necessary fields and complied with the guidelines. Failure to comply may result in the request being closed without discussion, and repeated violations may lead to restrict account from further participation.**

**Comment by dayanch96** [comment]
Hey. There already stock button for that

**Comment by ev0tto** [comment]
> Hey. There already stock button for that

Pressing the button on the thumbnail temporarily disables it, but after restarting the app, it shows up again. It’s annoying—could we have an option to keep it off by default? Or hide it altogether.

**Comment by dayanch96** [comment]
Will see. If there simple way to remember it - i will make it. But i don't want to add option for that - settings going to be messy. I still have to sort it properly

**Comment by ev0tto** [comment]
I see, thank you.
