### ISSUE TITLE
[Shorts Tab] App crash - on jumping to next shorts

### ISSUE THREAD

**Issue by bachig26** [dayanch96/YTLite#182]
### Describe the bug

```yaml
When the swiping up to jump to a new shorts or the shorts scroll to next automatically, the app crashed. this bug was/ is present on both v5.0.1 and v5.0.2.
I build the app myself on last few versions and also tried with the tweak app "[YTLitePlus](https://github.com/YTLitePlus/YTLitePlus)", and found the problem lies with the YTLite.
```

### Steps to reproduce

```yaml
1. Go to Shorts Tab
2. Scroll to next Shorts or use the "Scroll to next" option
3. When the current Shorts end, the app crashes on trying to move to next Shorts
```

### Crashlog

{"app_name":"YouTube","timestamp":"2024-09-10 11:09:25.00 +0530","app_version":"19.35.3","slice_uuid":"14738851-222d-3b99-a2c4-636a5029a587","build_version":"19.35.3","platform":2,"bundleID":"com.google.ios.youtube.CMG56SVCQ9","share_with_app_devs":0,"is_first_party":0,"bug_type":"309","os_version":"iPhone OS 15.8.3 (19H386)","incident_id":"2787C6BC-A236-46A4-91AB-6BDA053DE22E","name":"YouTube"}
{
  "uptime" : 290000,
  "procLaunch" : "2024-09-10 11:09:07.1817 +0530",
  "procRole" : "Foreground",
  "version" : 2,
  "userID" : 501,
  "deployVersion" : 210,
  "modelCode" : "iPhone8,4",
  "procStartAbsTime" : 6962582662152,
  "coalitionID" : 1226,
  "osVersion" : {
    "isEmbedded" : true,
    "train" : "iPhone OS 15.8.3",
    "releaseType" : "User",
    "build" : "19H386"
  },
  "captureTime" : "2024-09-10 11:09:21.1799 +0530",
  "incident" : "2787C6BC-A236-46A4-91AB-6BDA053DE22E",
  "bug_type" : "309",
  "pid" : 63767,
  "procExitAbsTime" : 6962918088684,
  "cpuType" : "ARM-64",
  "procName" : "YouTube",
  "procPath" : "\/private\/var\/containers\/Bundle\/Application\/734C7858-60F8-4EE0-B166-A68AD984937E\/App.app\/YouTube",
  "bundleInfo" : {"CFBundleShortVersionString":"19.35.3","CFBundleVersion":"19.35.3","CFBundleIdentifier":"com.google.ios.youtube.CMG56SVCQ9","DTAppStoreToolsBuild":"15F31e"},
  "storeInfo" : {"deviceIdentifierForVendor":"C327C7EF-22F2-4D17-9CF3-C9E958BD058E","thirdParty":true},
  "parentProc" : "launchd",
  "parentPid" : 1,
  "coalitionName" : "com.google.ios.youtube.CMG56SVCQ9",
  "crashReporterKey" : "01f1cfc8c7112de950753e74ff2a6a5a2f0ae37e",
  "basebandVersion" : "11.61.01",
  "isCorpse" : 1,
  "exception" : {"codes":"0x0000000000000000, 0x0000000000000000","rawCodes":[0,0],"type":"EXC_CRASH","signal":"SIGABRT"},
  "asi" : {"libsystem_c.dylib":["abort() called"]},
  "faultingThread" : 0,
  "threads" : [{"triggered":true,"id":2215873,"threadState":{"x":[{"value":0},{"value":0},{"value":0},{"value":0},{"value":6847753889},{"value":6125675552},{"value":110},{"value":6125676056},{"value":4508681600,"symbolLocation":0,"symbol":"_main_thread"},{"value":4455441386697009602},{"value":512},{"value":11},{"value":0},{"value":0},{"value":16},{"value":0},{"value":328},{"value":1},{"value":0},{"value":6},{"value":259},{"value":4508681824,"symbolLocation":224,"symbol":"_main_thread"},{"value":10791187776},{"value":0},{"value":50331647},{"value":4508681824,"symbolLocation":224,"symbol":"_main_thread"},{"value":15},{"value":10791187776},{"value":0}],"flavor":"ARM_THREAD_STATE64","lr":{"value":7983384644},"cpsr":{"value":1073741824},"fp":{"value":6125675408},"sp":{"value":6125675376},"esr":{"value":1442840704,"description":" Address size fault"},"pc":{"value":7434533820,"matchesCrashFrame":1},"far":{"value":8430893384}},"frames":[{"imageOffset":27580,"imageIndex":0},{"imageOffset":128684,"symbol":"abort","symbolLocation":124,"imageIndex":1},{"imageOffset":69092,"symbol":"abort_message","symbolLocation":128,"imageIndex":2},{"imageOffset":5764,"symbol":"demangling_terminate_handler()","symbolLocation":300,"imageIndex":2},{"imageOffset":108792,"symbol":"_objc_terminate()","symbolLocation":124,"imageIndex":3},{"imageOffset":66176,"symbol":"std::__terminate(void (*)())","symbolLocation":16,"imageIndex":2},{"imageOffset":66088,"symbol":"std::terminate()","symbolLocation":60,"imageIndex":2},{"imageOffset":409768,"imageIndex":4},{"imageOffset":68932,"imageIndex":4},{"imageOffset":67988,"imageIndex":4},{"imageOffset":319508,"imageIndex":5},{"imageOffset":46328,"imageIndex":5},{"imageOffset":123252,"imageIndex":5},{"imageOffset":6536,"symbol":"GSEventRunModal","symbolLocation":160,"imageIndex":6},{"imageOffset":5134984,"symbol":"-[UIApplication _run]","symbolLocation":1080,"imageIndex":7},{"imageOffset":2617208,"symbol":"UIApplicationMain","symbolLocation":336,"imageIndex":7},{"imageOffset":859632,"imageIndex":8},{"imageOffset":99536,"symbol":"start","symbolLocation":444,"imageIndex":9}]},{"id":2215878,"frames":[{"imageOffset":6436,"imageIndex":10}]},{"id":2215879,"name":"com.apple.uikit.eventfetch-thread","frames":[{"imageOffset":2732,"imageIndex":0},{"imageOffset":27784,"imageIndex":5},{"imageOffset":44944,"imageIndex":5},{"imageOffset":123252,"imageIndex":5},{"imageOffset":97964,"symbol":"-[NSRunLoop(NSRunLoop) runMode:beforeDate:]","symbolLocation":232,"imageIndex":11},{"imageOffset":356304,"symbol":"-[NSRunLoop(NSRunLoop) runUntilDate:]","symbolLocation":88,"imageIndex":11},{"imageOffset":4607732,"symbol":"-[UIEventFetcher threadMain]","symbolLocation":512,"imageIndex":7},{"imageOffset":412636,"symbol":"__NSThread__start__","symbolLocation":792,"imageIndex":11},{"imageOffset":13112,"imageIndex":10},{"imageOffset":6456,"imageIndex":10}]},{"id":2215882,"frames":[{"imageOffset":6436,"imageIndex":10}]},{"id":2215885,"frames":[{"imageOffset":6436,"imageIndex":10}]},{"id":2215886,"frames":[{"imageOffset":6436,"imageIndex":10}]},{"id":2215889,"name":"V8 DefaultWorke","frames":[{"imageOffset":5252,"imageIndex":0},{"imageOffset":1376692,"imageIndex":8},{"imageOffset":1376360,"imageIndex":8},{"imageOffset":1376304,"imageIndex":8},{"imageOffset":13112,"imageIndex":10},{"imageOffset":6456,"imageIndex":10}]},{"id":2215892,"name":"AVAudioSession Notify Thread","frames":[{"imageOffset":2732,"imageIndex":0},{"imageOffset":27784,"imageIndex":5},{"imageOffset":44944,"imageIndex":5},{"imageOffset":123252,"imageIndex":5},{"imageOffset":25720,"symbol":"CADeprecated::GenericRunLoopThread::Entry(void*)","symbolLocation":156,"imageIndex":12},{"imageOffset":63432,"symbol":"CADeprecated::CAPThread::Entry(CADeprecated::CAPThread*)","symbolLocation":88,"imageIndex":12},{"imageOffset":13112,"imageIndex":10},{"imageOffset":6456,"imageIndex":10}]},{"id":2215893,"frames":[{"imageOffset":2732,"imageIndex":0},{"imageOffset":2366588,"imageIndex":8},{"imageOffset":2365296,"imageIndex":8},{"imageOffset":2362636,"imageIndex":8},{"imageOffset":2362468,"imageIndex":8},{"imageOffset":13112,"imageIndex":10},{"imageOffset":6456,"imageIndex":10}]},{"id":2215897,"name":"JSInstanceDisposer","frames":[{"imageOffset":5252,"imageIndex":0},{"imageOffset":3413100,"imageIndex":8},{"imageOffset":3412868,"imageIndex":8},{"imageOffset":3412624,"imageIndex":8},{"imageOffset":3012408,"imageIndex":8},{"imageOffset":3408928,"imageIndex":8},{"imageOffset":3407908,"imageIndex":8},{"imageOffset":13112,"imageIndex":10},{"imageOffset":6456,"imageIndex":10}]},{"id":2215902,"frames":[{"imageOffset":6436,"imageIndex":10}]},{"id":2215903,"frames":[{"imageOffset":2816,"imageIndex":0},{"imageOffset":20324,"imageIndex":4},{"imageOffset":40387676,"imageIndex":8},{"imageOffset":91463428,"imageIndex":8},{"imageOffset":2362468,"imageIndex":8},{"imageOffset":13112,"imageIndex":10},{"imageOffset":6456,"imageIndex":10}]},{"id":2215906,"name":"com.apple.NSURLConnectionLoader","frames":[{"imageOffset":2732,"imageIndex":0},{"imageOffset":27784,"imageIndex":5},{"imageOffset":44944,"imageIndex":5},{"imageOffset":123252,"imageIndex":5},{"imageOffset":2386844,"imageIndex":13},{"imageOffset":412636,"symbol":"__NSThread__start__","symbolLocation":792,"imageIndex":11},{"imageOffset":13112,"imageIndex":10},{"imageOffset":6456,"imageIndex":10}]},{"id":2215912,"name":"com.apple.CFSocket.private","frames":[{"imageOffset":5808,"imageIndex":0},{"imageOffset":13112,"imageIndex":10},{"imageOffset":6456,"imageIndex":10}]},{"id":2215931,"name":"ThreadPoolServiceThread","frames":[{"imageOffset":2732,"imageIndex":0},{"imageOffset":27784,"imageIndex":5},{"imageOffset":44944,"imageIndex":5},{"imageOffset":123252,"imageIndex":5},{"imageOffset":97964,"symbol":"-[NSRunLoop(NSRunLoop) runMode:beforeDate:]","symbolLocation":232,"imageIndex":11},{"imageOffset":7147528,"imageIndex":8},{"imageOffset":7141372,"imageIndex":8},{"imageOffset":6843228,"imageIndex":8},{"imageOffset":6639008,"imageIndex":8},{"imageOffset":6986776,"imageIndex":8},{"imageOffset":6898952,"imageIndex":8},{"imageOffset":6987072,"imageIndex":8},{"imageOffset":7119016,"imageIndex":8},{"imageOffset":13112,"imageIndex":10},{"imageOffset":6456,"imageIndex":10}]},{"id":2215932,"name":"ThreadPoolForegroundWorker","frames":[{"imageOffset":2732,"imageIndex":0},{"imageOffset":7155864,"imageIndex":8},{"imageOffset":6936380,"imageIndex":8},{"imageOffset":6939336,"imageIndex":8},{"imageOffset":6938428,"imageIndex":8},{"imageOffset":6938160,"imageIndex":8},{"imageOffset":7119016,"imageIndex":8},{"imageOffset":13112,"imageIndex":10},{"imageOffset":6456,"imageIndex":10}]},{"id":2215933,"name":"ThreadPoolBackgroundWorker","frames":[{"imageOffset":2732,"imageIndex":0},{"imageOffset":7155864,"imageIndex":8},{"imageOffset":6936380,"imageIndex":8},{"imageOffset":6938820,"imageIndex":8},{"imageOffset":6938296,"imageIndex":8},{"imageOffset":6938208,"imageIndex":8},{"imageOffset":7119016,"imageIndex":8},{"imageOffset":13112,"imageIndex":10},{"imageOffset":6456,"imageIndex":10}]},{"id":2215934,"name":"NetworkConfigWatcher","frames":[{"imageOffset":2732,"imageIndex":0},{"imageOffset":27784,"imageIndex":5},{"imageOffset":44944,"imageIndex":5},{"imageOffset":123252,"imageIndex":5},{"imageOffset":97964,"symbol":"-[NSRunLoop(NSRunLoop) runMode:beforeDate:]","symbolLocation":232,"imageIndex":11},{"imageOffset":7147528,"imageIndex":8},{"imageOffset":7141372,"imageIndex":8},{"imageOffset":6843228,"imageIndex":8},{"imageOffset":6639008,"imageIndex":8},{"imageOffset":6986776,"imageIndex":8},{"imageOffset":6987072,"imageIndex":8},{"imageOffset":7119016,"imageIndex":8},{"imageOffset":13112,"imageIndex":10},{"imageOffset":6456,"imageIndex":10}]},{"id":2215935,"name":"network","frames":[{"imageOffset":2732,"imageIndex":0},{"imageOffset":27784,"imageIndex":5},{"imageOffset":44944,"imageIndex":5},{"imageOffset":123252,"imageIndex":5},{"imageOffset":97964,"symbol":"-[NSRunLoop(NSRunLoop) runMode:beforeDate:]","symbolLocation":232,"imageIndex":11},{"imageOffset":7147528,"imageIndex":8},{"imageOffset":7141372,"imageIndex":8},{"imageOffset":6843228,"imageIndex":8},{"imageOffset":6639008,"imageIndex":8},{"imageOffset":6986776,"imageIndex":8},{"imageOffset":6987072,"imageIndex":8},{"imageOffset":7119016,"imageIndex":8},{"imageOffset":13112,"imageIndex":10},{"imageOffset":6456,"imageIndex":10}]},{"id":2215936,"name":"Network File Thread","frames":[{"imageOffset":2732,"imageIndex":0},{"imageOffset":27784,"imageIndex":5},{"imageOffset":44944,"imageIndex":5},{"imageOffset":123252,"imageIndex":5},{"imageOffset":7146600,"imageIndex":8},{"imageOffset":7141372,"imageIndex":8},{"imageOffset":6843228,"imageIndex":8},{"imageOffset":6639008,"imageIndex":8},{"imageOffset":6986776,"imageIndex":8},{"imageOffset":6987072,"imageIndex":8},{"imageOffset":7119016,"imageIndex":8},{"imageOffset":13112,"imageIndex":10},{"imageOffset":6456,"imageIndex":10}]},{"id":2215947,"name":"ThreadPoolForegroundWorker","frames":[{"imageOffset":2732,"imageIndex":0},{"imageOffset":7155864,"imageIndex":8},{"imageOffset":6936380,"imageIndex":8},{"imageOffset":6939336,"imageIndex":8},{"imageOffset":6938428,"imageIndex":8},{"imageOffset":6938160,"imageIndex":8},{"imageOffset":7119016,"imageIndex":8},{"imageOffset":13112,"imageIndex":10},{"imageOffset":6456,"imageIndex":10}]},{"id":2215949,"name":"ThreadPoolForegroundWorker","frames":[{"imageOffset":2732,"imageIndex":0},{"imageOffset":7155864,"imageIndex":8},{"imageOffset":6936380,"imageIndex":8},{"imageOffset":6939336,"imageIndex":8},{"imageOffset":6938428,"imageIndex":8},{"imageOffset":6938160,"imageIndex":8},{"imageOffset":7119016,"imageIndex":8},{"imageOffset":13112,"imageIndex":10},{"imageOffset":6456,"imageIndex":10}]},{"id":2215950,"name":"ThreadPoolForegroundWorker","frames":[{"imageOffset":2732,"imageIndex":0},{"imageOffset":7155864,"imageIndex":8},{"imageOffset":6936380,"imageIndex":8},{"imageOffset":6938820,"imageIndex":8},{"imageOffset":6938428,"imageIndex":8},{"imageOffset":6938160,"imageIndex":8},{"imageOffset":7119016,"imageIndex":8},{"imageOffset":13112,"imageIndex":10},{"imageOffset":6456,"imageIndex":10}]},{"id":2215952,"name":"com.apple.coremedia.rootQueue.47","frames":[{"imageOffset":2816,"imageIndex":0},{"imageOffset":20324,"imageIndex":4},{"imageOffset":80272,"imageIndex":4},{"imageOffset":13112,"imageIndex":10},{"imageOffset":6456,"imageIndex":10}]},{"id":2215954,"name":"com.apple.coremedia.rootQueue.47","frames":[{"imageOffset":2816,"imageIndex":0},{"imageOffset":20324,"imageIndex":4},{"imageOffset":80272,"imageIndex":4},{"imageOffset":13112,"imageIndex":10},{"imageOffset":6456,"imageIndex":10}]},{"id":2215965,"name":"com.apple.coremedia.rootQueue.47","frames":[{"imageOffset":2816,"imageIndex":0},{"imageOffset":20324,"imageIndex":4},{"imageOffset":80272,"imageIndex":4},{"imageOffset":13112,"imageIndex":10},{"imageOffset":6456,"imageIndex":10}]},{"id":2216018,"name":"JavaScriptCore libpas scavenger","frames":[{"imageOffset":5252,"imageIndex":0},{"imageOffset":938024,"symbol":"scavenger_thread_main","symbolLocation":960,"imageIndex":14},{"imageOffset":13112,"imageIndex":10},{"imageOffset":6456,"imageIndex":10}]},{"id":2216019,"name":"Heap Helper Thread","frames":[{"imageOffset":5252,"imageIndex":0},{"imageOffset":301220,"symbol":"WTF::ParkingLot::parkConditionallyImpl(void const*, WTF::ScopedLambda<bool ()> const&, WTF::ScopedLambda<void ()> const&, WTF::TimeWithDynamicClockType const&)","symbolLocation":1984,"imageIndex":14},{"imageOffset":71468,"symbol":"bool WTF::Condition::waitUntilUnchecked<WTF::Lock>(WTF::Lock&, WTF::TimeWithDynamicClockType const&)","symbolLocation":176,"imageIndex":14},{"imageOffset":72572,"symbol":"WTF::Detail::CallableWrapper<WTF::AutomaticThread::start(WTF::AbstractLocker const&)::$_0, void>::call()","symbolLocation":328,"imageIndex":14},{"imageOffset":432404,"symbol":"WTF::Thread::entryPoint(WTF::Thread::NewThreadContext*)","symbolLocation":336,"imageIndex":14},{"imageOffset":441324,"symbol":"WTF::wtfThreadEntryPoint(void*)","symbolLocation":12,"imageIndex":14},{"imageOffset":13112,"imageIndex":10},{"imageOffset":6456,"imageIndex":10}]},{"id":2216036,"frames":[{"imageOffset":6436,"imageIndex":10}]},{"id":2216037,"frames":[{"imageOffset":6436,"imageIndex":10}]},{"id":2216039,"frames":[{"imageOffset":6436,"imageIndex":10}]}],
  "usedImages" : [
  {
    "source" : "P",
    "arch" : "arm64",
    "base" : 7434506240,
    "size" : 212992,
    "uuid" : "102e8613-6676-33f6-a0b4-f6e86a8636ce",
    "path" : "\/usr\/lib\/system\/libsystem_kernel.dylib",
    "name" : "libsystem_kernel.dylib"
  },
  {
    "source" : "P",
    "arch" : "arm64",
    "base" : 6627168256,
    "size" : 507904,
    "uuid" : "f90936ac-0df4-38ae-b3ea-2cd6e5f97e64",
    "path" : "\/usr\/lib\/system\/libsystem_c.dylib",
    "name" : "libsystem_c.dylib"
  },
  {
    "source" : "P",
    "arch" : "arm64",
    "base" : 6847672320,
    "size" : 94208,
    "uuid" : "f92ef016-d0cd-3182-9fc0-1ec48f372556",
    "path" : "\/usr\/lib\/libc++abi.dylib",
    "name" : "libc++abi.dylib"
  },
  {
    "source" : "P",
    "arch" : "arm64",
    "base" : 6846640128,
    "size" : 229376,
    "uuid" : "f1b36686-ed48-35ef-8896-0cea8e9da1c0",
    "path" : "\/usr\/lib\/libobjc.A.dylib",
    "name" : "libobjc.A.dylib"
  },
  {
    "source" : "P",
    "arch" : "arm64",
    "base" : 6448447488,
    "size" : 536576,
    "uuid" : "9ccdbde3-15e1-3a45-b330-4a5e2c3f92bd",
    "path" : "\/usr\/lib\/system\/libdispatch.dylib",
    "name" : "libdispatch.dylib"
  },
  {
    "source" : "P",
    "arch" : "arm64",
    "base" : 6451662848,
    "size" : 4448256,
    "uuid" : "eec1287d-059b-38c8-9bc1-58a0c8b1e6c2",
    "path" : "\/System\/Library\/Frameworks\/CoreFoundation.framework\/CoreFoundation",
    "name" : "CoreFoundation"
  },
  {
    "source" : "P",
    "arch" : "arm64",
    "base" : 7000313856,
    "size" : 36864,
    "uuid" : "bb434d86-0991-365f-bed3-c3923cf3073c",
    "path" : "\/System\/Library\/PrivateFrameworks\/GraphicsServices.framework\/GraphicsServices",
    "name" : "GraphicsServices"
  },
  {
    "source" : "P",
    "arch" : "arm64",
    "base" : 6488604672,
    "size" : 24756224,
    "uuid" : "9d301877-2593-385c-8f72-f075aa0b48fa",
    "path" : "\/System\/Library\/PrivateFrameworks\/UIKitCore.framework\/UIKitCore",
    "name" : "UIKitCore"
  },
  {
    "source" : "P",
    "arch" : "arm64",
    "base" : 4341202944,
    "size" : 135331840,
    "uuid" : "14738851-222d-3b99-a2c4-636a5029a587",
    "path" : "\/private\/var\/containers\/Bundle\/Application\/734C7858-60F8-4EE0-B166-A68AD984937E\/App.app\/YouTube",
    "name" : "YouTube"
  },
  {
    "source" : "P",
    "arch" : "arm64",
    "base" : 4508254208,
    "size" : 344064,
    "uuid" : "16c8ea1a-1c77-3f4f-97a6-6ae7fb25eb29",
    "path" : "\/usr\/lib\/dyld",
    "name" : "dyld"
  },
  {
    "source" : "P",
    "arch" : "arm64",
    "base" : 7983329280,
    "size" : 69632,
    "uuid" : "6679a5b3-a40a-37a7-b1c5-565a0f5cb6ab",
    "path" : "\/usr\/lib\/system\/libsystem_pthread.dylib",
    "name" : "libsystem_pthread.dylib"
  },
  {
    "source" : "P",
    "arch" : "arm64",
    "base" : 6475857920,
    "size" : 3035136,
    "uuid" : "f9235fc7-ec4e-31c9-b56e-95cf10b07239",
    "path" : "\/System\/Library\/Frameworks\/Foundation.framework\/Foundation",
    "name" : "Foundation"
  },
  {
    "source" : "P",
    "arch" : "arm64",
    "base" : 6600310784,
    "size" : 167936,
    "uuid" : "43120808-d624-31fe-a865-b0e4b154a63a",
    "path" : "\/System\/Library\/PrivateFrameworks\/AudioSession.framework\/AudioSession",
    "name" : "AudioSession"
  },
  {
    "source" : "P",
    "arch" : "arm64",
    "base" : 6459904000,
    "size" : 4784128,
    "uuid" : "db182cd7-f433-39ad-9531-e81430e96a77",
    "path" : "\/System\/Library\/Frameworks\/CFNetwork.framework\/CFNetwork",
    "name" : "CFNetwork"
  },
  {
    "source" : "P",
    "arch" : "arm64",
    "base" : 6628016128,
    "size" : 20484096,
    "uuid" : "e00aba4f-5f03-3fcd-9566-9793ae6ad805",
    "path" : "\/System\/Library\/Frameworks\/JavaScriptCore.framework\/JavaScriptCore",
    "name" : "JavaScriptCore"
  }
],
  "sharedCache" : {
  "base" : 6448119808,
  "size" : 2323562496,
  "uuid" : "870e05c6-817e-3cc0-a84f-768a252872b0"
},
  "vmSummary" : "ReadOnly portion of Libraries: Total=985.7M resident=0K(0%) swapped_out_or_unallocated=985.7M(100%)\nWritable regions: Total=925.2M written=0K(0%) resident=0K(0%) swapped_out=0K(0%) unallocated=925.2M(100%)\n\n                                VIRTUAL   REGION \nREGION TYPE                        SIZE    COUNT (non-coalesced) \n===========                     =======  ======= \nAccelerate framework               128K        1 \nActivity Tracing                   256K        1 \nCG image                           912K        1 \nCG raster data                    5248K       24 \nColorSync                          112K        7 \nCoreAnimation                      736K       34 \nCoreData                           160K        5 \nCoreData Object IDs               4112K        2 \nCoreUI image data                  480K        5 \nFoundation                         432K        5 \nImage IO                           160K        5 \nKernel Alloc Once                   32K        1 \nMALLOC                           594.4M     1117 \nMALLOC guard page                  192K       12 \nMach message                        16K        1 \nMemory Tag 255                    3216K       23 \nSQLite page cache                 1472K       23 \nSTACK GUARD                       1504K       31 \nStack                             18.8M       34 \nVM_ALLOCATE                        336K        5 \nWebKit Malloc                    224.0M        6 \nWebKit Malloc (reserved)          64.0M        1         reserved VM address space (unallocated)\n__CTF                               756        1 \n__DATA                            54.0M      711 \n__DATA_CONST                      67.5M      725 \n__DATA_DIRTY                      2856K      603 \n__ETC                              112K        1 \n__FONT_DATA                          4K        1 \n__LINKEDIT                       190.3M        9 \n__OBJC_RO                         91.9M        1 \n__OBJC_RW                         3520K        1 \n__TEXT                           795.4M      733 \n__UNICODE                          592K        1 \ndyld private memory               1024K        1 \nlibnetwork                        1664K       24 \nmapped file                      187.4M       31 \nshared memory                       48K        3 \n===========                     =======  ======= \nTOTAL                              2.3G     4190 \nTOTAL, minus reserved VM space     2.2G     4190 \n",
  "legacyInfo" : {
  "threadTriggered" : {

  }
},
  "trialInfo" : {
  "rollouts" : [
    {
      "rolloutId" : "61030413bfe6dc472e1c980c",
      "factorPackIds" : {

      },
      "deploymentId" : 240000489
    },
    {
      "rolloutId" : "60da5e84ab0ca017dace9abf",
      "factorPackIds" : {

      },
      "deploymentId" : 240000008
    }
  ],
  "experiments" : [
    {
      "treatmentId" : "c47ab4cc-c9c3-4b5d-a87c-e2433ce02597",
      "experimentId" : "6639bc6ba73d460582162323",
      "deploymentId" : 400000006
    }
  ]
}
}

### Post Requisites

- [X] I have checked that a similar issue has not been reported before.
- [X] Verified the relevance of the project and the version you are using.
- [X] Provided a detailed description of the problem and have filled in all required fields.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.
- [X] By submitting this issue, **I confirm that I have filled in all the necessary fields and complied with the guidelines. Failure to comply may result in the issue being closed without discussion, and repeated violations may lead to restrict account from further participation.**

**Comment by dayanch96** [comment]
Hey! The issue will be resolved starting with the 5.1 beta versions.

For now, you can fix it by disabling Legacy support in the YouPiP settings.

Also, please make sure to read the instructions carefully before submitting an issue to avoid unnecessarily long reports. I won’t be reviewing any of those in the future. Thanks for your understanding!

<img width="942" alt="SS 2024-09-10 в 13 32 02" src="https://github.com/user-attachments/assets/0e99c896-f32c-4553-a1d8-516bc11c356b">
