### ISSUE TITLE
Sponsorblock crashes YouTube

### ISSUE THREAD

**Issue by c12n** [dayanch96/YTLite#190]
### Describe the bug

```yaml
Enabling sponsorblock inside 5.0.2 crashes YouTube
```

### Steps to reproduce

```yaml
1. Go to YouTube plus settings 
2. Open sponsorblock 
3. Turn it on 
4. YouTube crashes
```

### Post Requisites

- [X] I have checked that a similar issue has not been reported before.
- [X] Verified the relevance of the project and the version you are using.
- [X] Provided a detailed description of the problem and have filled in all required fields.
- [X] I did not answer truthfully to **ALL** the above checkboxes.
- [X] By submitting this issue, **I confirm that I have filled in all the necessary fields and complied with the guidelines. Failure to comply may result in the issue being closed without discussion, and repeated violations may lead to restrict account from further participation.**

**Comment by dayanch96** [comment]
#183
