### ISSUE TITLE
Add open borders n YouTube extension

### ISSUE THREAD

**Issue by tonysprenk** [dayanch96/YTLite#192]
### Describe the feature request

```yaml
Would be nice to be able to automatically open YouTube links in ytlite

https://github.com/CokePokes/YoutubeExtensions
```

### Post Requisites

- [X] I have checked that a similar feature request has not been reported before.
- [X] Verified the relevance of the project and the version you are using.
- [X] Provided a detailed description of the request and have filled in all required fields.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.
- [X] By submitting this request, **I confirm that I have filled in all the necessary fields and complied with the guidelines. Failure to comply may result in the request being closed without discussion, and repeated violations may lead to restrict account from further participation.**

**Comment by dayanch96** [comment]
It’s already included
