### ISSUE TITLE
Blank covers even using Fix covers feature

### ISSUE THREAD

**Issue by romantra** [dayanch96/YTLite#193]
### Describe the bug

```yaml
Starting today Sept 23 2024 I'm getting blank covers in shorts and regular videos, and also my phone is strangely getting very hot viewing videos. I'm enabled the fix cover feature but no changes showing.
```

### Steps to reproduce

```yaml
Example:
Open app
Slide up and down to see covers
Click on a video or short 
Your phone will get hot
```

### Crashlog

![IMG_3458](https://github.com/user-attachments/assets/c57de012-2791-4dd3-b486-2bb8ac5db8d8)

### Post Requisites

- [X] I have checked that a similar issue has not been reported before.
- [X] Verified the relevance of the project and the version you are using.
- [X] Provided a detailed description of the problem and have filled in all required fields.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.
- [X] By submitting this issue, **I confirm that I have filled in all the necessary fields and complied with the guidelines. Failure to comply may result in the issue being closed without discussion, and repeated violations may lead to restrict account from further participation.**

**Comment by dayanch96** [comment]
Don’t use it if you’re not from Russia

**Comment by dayanch96** [comment]
Hey @romantra

Based on your reaction to my response, it seems you may have misunderstood me. I’ve updated the message for clarity and will explain further:

Enabling `Fix covers` feature is not necessary for you and not recommended unless you're in Russia. It's only needed for users from Russia to replace addresses for previews.
