### ISSUE TITLE
White bar persists in full screen playback

### ISSUE THREAD

**Issue by dhcho94** [dayanch96/YTLite#194]
### Describe the bug

```yaml
When watching videos in fullscreen on my iPhone 15 pro, the white bar at the bottom does not disappear as it should. YT version is 19.37.2 and 5.0.2

One workaround I found so far is to sign out of YouTube, enable the old ui, restart, disable old ui, and then log back in. However, this is only temporary as the white bar doesn’t disappear again after some time.
```

### Steps to reproduce

```yaml
1. Watch a video in fullscreen

2. White bar appears at the bottom and doesn’t go away.
```

### Post Requisites

- [X] I have checked that a similar issue has not been reported before.
- [X] Verified the relevance of the project and the version you are using.
- [X] Provided a detailed description of the problem and have filled in all required fields.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.
- [X] By submitting this issue, **I confirm that I have filled in all the necessary fields and complied with the guidelines. Failure to comply may result in the issue being closed without discussion, and repeated violations may lead to restrict account from further participation.**

**Comment by dayanch96** [comment]
Changed label to https://github.com/dayanch96/YTLite/labels/enhancement since its not a bug, but probably AB feature

**Comment by dhcho94** [comment]
Don’t know what fixed it but haven’t had this issue since posting this lol
