### ISSUE TITLE
Post won't go fullscreen when pressed

### ISSUE THREAD

**Issue by GrPK** [dayanch96/YTLite#195]
### Describe the bug

```yaml
Hello! On stock app, whenever the user presses a post, the image will enlarge and go full-screen.

However, on 5.0.2 this won't happen, pressing the photo doesn't do anything.

Do I miss a setting somewhere?
```

### Steps to reproduce

```yaml
Example:

1. Find a post with photos attached
2. Click on a post
```

### Post Requisites

- [X] I have checked that a similar issue has not been reported before.
- [X] Verified the relevance of the project and the version you are using.
- [X] Provided a detailed description of the problem and have filled in all required fields.
- [X] I did not answer truthfully to **ALL** the above checkboxes.
- [X] By submitting this issue, **I confirm that I have filled in all the necessary fields and complied with the guidelines. Failure to comply may result in the issue being closed without discussion, and repeated violations may lead to restrict account from further participation.**

**Comment by GrPK** [comment]
![photo_2024-09-25_21-37-03](https://github.com/user-attachments/assets/faee5345-2701-4d85-b536-84e1fc9a4748)

On posts like this one

**Comment by dayanch96** [comment]
Its not tweak but vanilla yt issue

**Comment by GrPK** [comment]
Actually I tried with YouTube 19.38.2 and the bug still persists in the modded version

**Comment by GrPK** [comment]
This bug is still present in 5.1 b2 btw... The stock app works as expected

**Comment by dayanch96** [comment]
Added image viewer: https://github.com/dayanch96/YTLite/releases/tag/v5.1

**Comment by mak448a** [comment]
Hey @dayanch96, is it possible to full screen without the “show image” option?

**Comment by dayanch96** [comment]
yes. but i don’t have plans on working on it. sorry. its google’s fault that they broke this feature

**Comment by FayeReagan** [comment]
Using appstore youtube or the old YTLite with OldUI, i can tap the images to see the full picture
But the latest version 5.1, long tap or long press doesn't show the "Show full-size post in image viewer" options like told on the changelog
I use YTPlus + Tweaks ipa from the altstore source

**Comment by Proaxel** [comment]
@dayanch96 I recently reinstalled 5.2b1 to fix Return Dislike crashing shorts and now the button to open the image viewer no longer appears when holding the image. Was it removed or am I missing a setting somewhere?

**Comment by dayanch96** [comment]
> [@dayanch96](https://github.com/dayanch96) I recently reinstalled 5.2b1 to fix Return Dislike crashing shorts and now the button to open the image viewer no longer appears when holding the image. Was it removed or am I missing a setting somewhere?

probably have to fix it on newest versions

**Comment by Proaxel** [comment]
@dayanch96 Correction: turns out it is controlled by a setting that is disabled by default. It's YouTubePlus > Downloading > Save Post Information. The ability to bring up the menu where the "show current image" button is located seems to be dependent on this setting; when it is disabled, nothing appears when holding a post image. 

If this is intended behavior, it would be nice if the name and description of the setting was changed to be more accurate, as well as having it be enabled by default so no one needs to remember to turn it on after every reinstall. 

If you'd like I could make this a separate issue so this is easier to keep track of

**Comment by Sonic24Master** [comment]
i am having this issue on ytlite version 5.2b1 with youtube version 20.23.3. i checked if it happened on the stock youtube app of the same version and it doesn't happen there
