### ISSUE TITLE
Cannot use YouTube's stock downloader to save video offline [Trying NOT to use YTPlus downloader]

### ISSUE THREAD

**Issue by Prakyy** [dayanch96/YTLite#196]
### Describe the bug

```yaml
Trying to download any YouTube video just gets stuck at the 'waiting to download...' stage. It downloads maybe 50% then proceeds to sit at waiting. I cannot pause and resume it, only cancel or delete the download options are available.

Video downloading works normally with the stock YouTube client.

Hi, this also doesn't seem to work on any other tweaked IPAs, is it possible for you to figure out what is happening? I tried looking at network logs in FLEX but couldn't find anything.
```

### Steps to reproduce

```yaml
1. Disable download manager from YouTube plus settings
2. Open any video
3. Click download and go to downloads tab
4. Find the video to not be downloading but 'waiting to download...'
```

### Post Requisites

- [X] I have checked that a similar issue has not been reported before.
- [X] Verified the relevance of the project and the version you are using.
- [X] Provided a detailed description of the problem and have filled in all required fields.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.
- [X] By submitting this issue, **I confirm that I have filled in all the necessary fields and complied with the guidelines. Failure to comply may result in the issue being closed without discussion, and repeated violations may lead to restrict account from further participation.**

**Comment by dayanch96** [comment]
Hey. Sorry, I don’t have Premium and it’s probably sideloaded apps issue

**Comment by Prakyy** [comment]
Is it possible to get a trial? And what would be the sideloading issue? I’m using a revoked enterprise cert (dns block). I really need smart downloads, how can I figure out what’s the issue? I checked sideloading the stock ipa and it doesn’t download there either.

I switched after a long time of android and was so used to revanced having no issues downloading videos.

You may close this issue if you’re not interested but I was hoping a dev would know what to do.

**Comment by dayanch96** [comment]
Sorry, no idea. Not familiar with it. Closing as not planned

**Comment by vikasbhatia** [comment]
@Prakyy [Try this, it might help you.](https://github.com/YTLitePlus/YTLitePlus/issues/428#issuecomment-2453108593) It worked for me but I had to build my own IPA from GitHub directly -- for some reason it didn't work with a pre-built one.
