### ISSUE TITLE
Would be possible to have a download manager? 

### ISSUE THREAD

**Issue by cerefen** [dayanch96/YTLite#198]
### Describe the feature request

```yaml
Would be possible to have a download manager tab option?  instead just saving in photos, or share sheet.

like DLtube, Dleasy YTkillerplus uYou, YTMusicultimate?

i would actually pay for this.

Thanks!
```

### Post Requisites

- [X] I have checked that a similar feature request has not been reported before.
- [X] Verified the relevance of the project and the version you are using.
- [X] Provided a detailed description of the request and have filled in all required fields.
- [X] I did not answer truthfully to **ALL** the above checkboxes.
- [X] By submitting this request, **I confirm that I have filled in all the necessary fields and complied with the guidelines. Failure to comply may result in the request being closed without discussion, and repeated violations may lead to restrict account from further participation.**

**Comment by dayanch96** [comment]
I would pay if you read requisites carefully next time - hehe, jk.

Sorry, not planned for now
