### ISSUE TITLE
[Request] Hide playlist/live chat/etc. right panel in full screen

### ISSUE THREAD

**Issue by casualsailo** [dayanch96/YTLite#199]
### Describe the feature request

```yaml
When playing a video inside a playlist and I switch to full screen mode, the playlist right panel pops open on the right half of the video. When opening a live stream and switching to full screen mode, the live chat pops open in full screen mode

I'm using YouTube Plus 5.0.2 and searched through the settings, but could not find a setting to hide/disable the right panel
```

### Post Requisites

- [X] I have checked that a similar feature request has not been reported before.
- [X] Verified the relevance of the project and the version you are using.
- [X] Provided a detailed description of the request and have filled in all required fields.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.
- [X] By submitting this request, **I confirm that I have filled in all the necessary fields and complied with the guidelines. Failure to comply may result in the request being closed without discussion, and repeated violations may lead to restrict account from further participation.**

**Comment by casualsailo** [comment]
![YouTube Playlist Right Panel](https://github.com/user-attachments/assets/4abb848b-cd4e-40ce-b9f6-37851fc39f49)
![YouTube Live Chat Right Panel](https://github.com/user-attachments/assets/236f429f-d7de-4e3c-8f0e-d6fe2bd9bb5f)

**Comment by dayanch96** [comment]
close engagement panel before entering fullscreen. Google's logic that if you haven't closed it, then you still need it
