### ISSUE TITLE
(Request) More speed options under "Extra Speed Options"

### ISSUE THREAD

**Issue by Usagyuuuun** [dayanch96/YTLite#20]
Would it be possible to add 3.25 and 3.75x speed options for the feature "Extra Speed Options"? I'm one of the weirdos who use it quite frequently.

Thank you to all the devs and contributor for this wonderful YT enhancer. Keep up the good work!

**Comment by dayanch96** [comment]
You can clone repository, open YTLite.x and add it manually in line 290

**Comment by dayanch96** [comment]
Please re-open if you'll have problems with it
