### ISSUE TITLE
Disabling “Preferred captions” make the language it chose can’t be enabled except when you switch language and switch back

### ISSUE THREAD

**Issue by dora727** [dayanch96/YTLite#203]
### Describe the bug

```yaml
When I set “Preferred captions” option to “Disabled”, I can’t manually enable the caption it automatically chose.
So I have to switch to other languages of it and switch back
```

### Steps to reproduce

```yaml
1. Go to Youtube Plus preferences
2. Set “Preferred captions” to “Disabled”
3. Open a video with 2 captions options
4. Try enable via the button on player (it doesn’t enable!)
5. Switch the language and it works now, switch back
```

### Post Requisites

- [X] I have checked that a similar issue has not been reported before.
- [X] Verified the relevance of the project and the version you are using.
- [X] Provided a detailed description of the problem and have filled in all required fields.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.
- [X] By submitting this issue, **I confirm that I have filled in all the necessary fields and complied with the guidelines. Failure to comply may result in the issue being closed without discussion, and repeated violations may lead to restrict account from further participation.**

**Comment by dayanch96** [comment]
Can't reproduce it. If you wait few seconds, it should try again if CC not available or audio-track reselected. any changes if you just give it 3-5 sec?

**Comment by dora727** [comment]
> Can't reproduce it. If you wait few seconds, it should try again if CC not available or audio-track reselected. any changes if you just give it 3-5 sec?

i did however nothing happened

**Comment by dayanch96** [comment]
screen record may help me reproduce this issue

**Comment by dora727** [comment]
since the file is larger than 10mb, i’ve decided to upload it into catbox

in the video what i did it disable caption, then open a video and select languages in both ways (holding the cc button, use the settings menu)
https://files.catbox.moe/ez9vka.mp4

**Comment by dayanch96** [comment]
Issue was with enabling via CC button... Anyway, completed here: https://github.com/dayanch96/YTLite/releases/tag/v5.1
