### ISSUE TITLE
Ability to play 1440p (2K) and 2160p (4K) videos

### ISSUE THREAD

**Issue by godly-devotion** [dayanch96/YTLite#204]
### Describe the feature request

```yaml
The iOS YouTube app seems to limit playback quality to 1080p despite high resolution screens available on the iPhone. Please allow playing videos in 1440p and 2160p resolutions as well.
```

### Post Requisites

- [X] I have checked that a similar feature request has not been reported before.
- [X] Verified the relevance of the project and the version you are using.
- [X] Provided a detailed description of the request and have filled in all required fields.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.
- [X] By submitting this request, **I confirm that I have filled in all the necessary fields and complied with the guidelines. Failure to comply may result in the request being closed without discussion, and repeated violations may lead to restrict account from further participation.**

**Comment by dayanch96** [comment]
Not possible.

All App Store apps, including sideloaded ones, require a special entitlement to use the VP9 codec, and only Apple can grant this entitlement. In Google’s case, Apple has granted this to their App Store account (team ID).

When you decrypt and resign an app using your own account, the app loses this special entitlement for VP9 support.

YTUHD relies on hardware acceleration. If your device isn’t powerful enough to download media, convert it in real-time to a supported format, and play it at the same time, you may and probably will experience buffering and overheating issues.

However, this doesn’t apply to the iPhone 15/16 PRO series, which natively support the AV1 codec without requiring any special entitlements.

You can try building IPA which includes YTUHD by using such workflow (Check readme on how to build ipa by yourself) or watch 4K videos via Safari

**Comment by godly-devotion** [comment]
Btw the regular A18 chip used in the iPhone 16/Plus **does** support hardware AV1 decode. So it's pretty reasonable to conclude that all models of iPhone 16 and newer will support AV1.

> **Video Playback**
> Supported formats include HEVC, H.264, and AV1

Reference https://www.apple.com/iphone-16/specs/

**Comment by godly-devotion** [comment]
I'm not sure if you can tell programmatically what iPhone version the user has but perhaps there could be a message saying YTUHD is supported only on `iPhone 15 Pro, iPhone 16 models or newer`.
