### ISSUE TITLE
Quality overlay not working 

### ISSUE THREAD

**Issue by mikajx** [dayanch96/YTLite#205]
### Describe the feature request

```yaml
Quality overlay selection not showing even activated in menu
```

### Post Requisites

- [X] I have checked that a similar feature request has not been reported before.
- [X] Verified the relevance of the project and the version you are using.
- [X] Provided a detailed description of the request and have filled in all required fields.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.
- [X] By submitting this request, **I confirm that I have filled in all the necessary fields and complied with the guidelines. Failure to comply may result in the request being closed without discussion, and repeated violations may lead to restrict account from further participation.**

**Comment by dayanch96** [comment]
There not and never was such feature. Consider using YouQuality for that
