### ISSUE TITLE
Youtube crashes because of "playback in feeds"

### ISSUE THREAD

**Issue by Hl220** [dayanch96/YTLite#211]
### Describe the bug

```yaml
when i started using YouTube plus (YTlite) There has been a bug when i open youtube and the videos load and i start to scroll It Crashes at first i didn't know why i tried to know what is causing the problem and found that its because of the "playback in feeds" i thinks its because of the download button doesn't load properly because sometimes it doesn't crashes me
```

### Steps to reproduce

```yaml
1.Go to settings
2.general settings
3.scroll down and disable "playback in feeds"
```

### Post Requisites

- [X] I have checked that a similar issue has not been reported before.
- [X] Verified the relevance of the project and the version you are using.
- [X] Provided a detailed description of the problem and have filled in all required fields.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.
- [X] By submitting this issue, **I confirm that I have filled in all the necessary fields and complied with the guidelines. Failure to comply may result in the issue being closed without discussion, and repeated violations may lead to restrict account from further participation.**

**Comment by dayanch96** [comment]
https://github.com/dayanch96/YTLite/issues/183

closing as its dublicate. fixed in beta already. will let you know additionally when on release

**Comment by Hl220** [comment]
Thanks 👍
