### ISSUE TITLE
Miniplayer = ON for “videos made for kids”

### ISSUE THREAD

**Issue by bachig26** [dayanch96/YTLite#213]
### Describe the feature request

```yaml
Since Miniplayer is turned off on default for the videos that has been marked as the videos made for kids.
I hope to see an option toggle is on to view the content on miniplayer as usual as other videos can be possible.
```

### Post Requisites

- [X] I have checked that a similar feature request has not been reported before.
- [X] Verified the relevance of the project and the version you are using.
- [X] Provided a detailed description of the request and have filled in all required fields.
- [X] I did not answer truthfully to **ALL** the above checkboxes.
- [X] By submitting this request, **I confirm that I have filled in all the necessary fields and complied with the guidelines. Failure to comply may result in the request being closed without discussion, and repeated violations may lead to restrict account from further participation.**

**Comment by dora727** [comment]
it does exists
<img width="375" alt="image" src="https://github.com/user-attachments/assets/97f496f1-6dc2-450b-9de4-ccc36ab51e48">

**Comment by dayanch96** [comment]
thanks @dora727
