### ISSUE TITLE
Color Your Seekbar

### ISSUE THREAD

**Issue by allorionmusic** [dayanch96/YTLite#214]
### Describe the feature request

```yaml
I saw another tweak (for android) having this feature.
It lets you change the color of your progress bar/seekbar, I have a screenshot of it in action: https://imgur.com/a/jg7JbQo
```

### Post Requisites

- [X] I have checked that a similar feature request has not been reported before.
- [X] Verified the relevance of the project and the version you are using.
- [X] Provided a detailed description of the request and have filled in all required fields.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.
- [X] By submitting this request, **I confirm that I have filled in all the necessary fields and complied with the guidelines. Failure to comply may result in the request being closed without discussion, and repeated violations may lead to restrict account from further participation.**

**Comment by dayanch96** [comment]
Will see, but no eta

**Comment by dayanch96** [comment]
Completed here: https://github.com/dayanch96/YTLite/releases/tag/v5.1
