### ISSUE TITLE
Add option to switch to old miniplayer

### ISSUE THREAD

**Issue by Neoncat-OG** [dayanch96/YTLite#215]
### Describe the feature request

```yaml
The new miniplayer is ugly and I hope you can add the option to switch back to the old bottom bar miniplayer. Any response would be greatly appreciated.

New miniplayer:
https://imgur.com/a/IDwpaPq

Old miniplayer:
https://imgur.com/a/bOF7nZ0
```

### Post Requisites

- [X] I have checked that a similar feature request has not been reported before.
- [X] Verified the relevance of the project and the version you are using.
- [X] Provided a detailed description of the request and have filled in all required fields.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.
- [X] By submitting this request, **I confirm that I have filled in all the necessary fields and complied with the guidelines. Failure to comply may result in the request being closed without discussion, and repeated violations may lead to restrict account from further participation.**

**Comment by hehbveh** [comment]
How do I get the beta?

**Comment by dayanch96** [comment]
Completed here: https://github.com/dayanch96/YTLite/releases/tag/v5.1

**Comment by dayanch96** [comment]
> How do I get the beta?

New betas coming soon on my patreon
