### ISSUE TITLE
Add an icon for YouTube Plus settings button

### ISSUE THREAD

**Issue by dora727** [dayanch96/YTLite#217]
### Describe the feature request

```yaml
So, in stock YouTube settings tab, they add icons for each settings button, it makes the UI looks good, also easier to access settings.

However, YTLite (YouTube Plus) doesn’t have one, and worse, it’ll make icons disappear and back to the old settings tab UI.

Some tweaks, such as RYD, YouPiP added, so I hope YouTube Plus also add one!
```

### Post Requisites

- [X] I have checked that a similar feature request has not been reported before.
- [X] Verified the relevance of the project and the version you are using.
- [X] Provided a detailed description of the request and have filled in all required fields.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.
- [X] By submitting this request, **I confirm that I have filled in all the necessary fields and complied with the guidelines. Failure to comply may result in the request being closed without discussion, and repeated violations may lead to restrict account from further participation.**

**Comment by dora727** [comment]
![IMG_0558](https://github.com/user-attachments/assets/f97ab18a-a690-45be-ab7d-94d4acbf1ab9)
![IMG_0559](https://github.com/user-attachments/assets/c676f33d-d54b-469e-8321-60d18c5423b0)

**Comment by dayanch96** [comment]
Looks nice, i will take a look

**Comment by dayanch96** [comment]
Completed here: https://github.com/dayanch96/YTLite/releases/tag/v5.1
