### ISSUE TITLE
Disable incompatibility warning if the built in sponsorblock is already disabled

### ISSUE THREAD

**Issue by olivertzeng** [dayanch96/YTLite#218]
### Describe the bug

```yaml
I want to use YTLite and iSponsorBlock simultaneously because I don’t really like the built in one rn. But even if you disable the built in SponsorBlock, it will still show the warning.
```

### Steps to reproduce

```yaml
1. Install iSponsorBlock
2. Install YTLite
3. Disable built in SponsorBlock
4. Still shows the warning
```

### Crashlog

Idk where it is but I’ll show screenshots
https://imgur.com/a/udEAD7M

### Post Requisites

- [X] I have checked that a similar issue has not been reported before.
- [X] Verified the relevance of the project and the version you are using.
- [X] Provided a detailed description of the problem and have filled in all required fields.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.
- [X] By submitting this issue, **I confirm that I have filled in all the necessary fields and complied with the guidelines. Failure to comply may result in the issue being closed without discussion, and repeated violations may lead to restrict account from further participation.**

**Comment by dayanch96** [comment]
Yup, unfortunately there no option to disable it for now

**Comment by IISAKNIFE** [comment]
> Yup, unfortunately there no option to disable it for now

Why not?
