### ISSUE TITLE
‘Your all caught up’ after watching a few shorts

### ISSUE THREAD

**Issue by balaajd** [dayanch96/YTLite#222]
### Describe the bug

```yaml
Hi, after opening the youtube app and watching a few shorts i cant scroll any further and it says ‘Your all caught up’
```

### Steps to reproduce

```yaml
1. open app
2. scroll through shorts
```

### Crashlog

[yt crash log.ips.zip](https://github.com/user-attachments/files/17596557/yt.crash.log.ips.zip)

### Post Requisites

- [X] I have checked that a similar issue has not been reported before.
- [X] Verified the relevance of the project and the version you are using.
- [X] Provided a detailed description of the problem and have filled in all required fields.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.
- [X] By submitting this issue, **I confirm that I have filled in all the necessary fields and complied with the guidelines. Failure to comply may result in the issue being closed without discussion, and repeated violations may lead to restrict account from further participation.**

**Comment by AushevAhmad** [comment]
Disable "Limit Shorts". Settings -> YouTube Plus -> Shorts
<img width="375" alt="image" src="https://github.com/user-attachments/assets/21f15a0a-b63a-4298-a8f8-6f5030d20e6b">

**Comment by dayanch96** [comment]
@AushevAhmad  thanks
