### ISSUE TITLE
iSponsor Block highlighting doesn't show in fullscreen on iphone

### ISSUE THREAD

**Issue by hwang1607** [dayanch96/YTLite#224]
### Describe the bug

```yaml
iSponsor Block highlighting doesn't show in fullscreen on iphone. It also disappears intermittently when in vertical mode

YouTube Plus 5.0.2
Youtube 19.43.2
```

### Steps to reproduce

```yaml
Enable iSponsor block highlighting, play a video with a sponsor
```

### Post Requisites

- [X] I have checked that a similar issue has not been reported before.
- [X] Verified the relevance of the project and the version you are using.
- [X] Provided a detailed description of the problem and have filled in all required fields.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.
- [X] By submitting this issue, **I confirm that I have filled in all the necessary fields and complied with the guidelines. Failure to comply may result in the issue being closed without discussion, and repeated violations may lead to restrict account from further participation.**

**Comment by dayanch96** [comment]
Completed here: https://github.com/dayanch96/YTLite/releases/tag/v5.1
