### ISSUE TITLE
macOS-12 is discontinued 

### ISSUE THREAD

**Issue by k3v1nwrld** [dayanch96/YTLite#226]
### Describe the bug

```yaml
The workflows of this repo use macos-12, which is not supported anymore by github. I tried using macos-15 but that gives an error...
```

### Steps to reproduce

```yaml
Run github actions
```

### Post Requisites

- [X] I have checked that a similar issue has not been reported before.
- [X] Verified the relevance of the project and the version you are using.
- [X] Provided a detailed description of the problem and have filled in all required fields.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.
- [X] By submitting this issue, **I confirm that I have filled in all the necessary fields and complied with the guidelines. Failure to comply may result in the issue being closed without discussion, and repeated violations may lead to restrict account from further participation.**

**Comment by difman62** [comment]
Depending on which building you want, YouTube Plus + YouPiP, YTUHD and RYD or the former, edit the .yml file which you can see in the summary page of the workflow you ran. 

Look for macos and change it to latest like macos-latest from macos-12

**Comment by k3v1nwrld** [comment]
> Depending on which building you want, YouTube Plus + YouPiP, YTUHD and RYD or the former, edit the .yml file which you can see in the summary page of the workflow you ran.
> 
> Look for macos and change it to latest like macos-latest from macos-12

The action still fails, but the problem is with YouPip which can't be compiled on macos 13+ (i think)

**Comment by difman62** [comment]
Yea same thing encountered on my side. I have let the owner know about this already. Something to resolve for later.

But at the meantime, you can use the first workflow to build your IPA.

**Comment by MrZomka** [comment]
YTUHD is another tweak that refuses to build on macos-15...

**Comment by MrZomka** [comment]
Updating Theos fixed it.

**Comment by MrZomka** [comment]
> Updating Theos fixed it.

Made a pull request. #237
