### ISSUE TITLE
Short descriptions showing next posts desc

### ISSUE THREAD

**Issue by Dark976** [dayanch96/YTLite#227]
### Describe the bug

```yaml
When i start watching shorts and youtube displays a sponsored post, it shows the next shorts header and description instead of the current post. Son when you go on you always see the next posts desc. Youtube version V19.44.4 , plus version 5.0.2
```

### Steps to reproduce

```yaml
Go to shorts and start going next post until u see an advertisement post, next you see the problem.
```

### Post Requisites

- [X] I have checked that a similar issue has not been reported before.
- [X] Verified the relevance of the project and the version you are using.
- [X] Provided a detailed description of the problem and have filled in all required fields.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.
- [X] By submitting this issue, **I confirm that I have filled in all the necessary fields and complied with the guidelines. Failure to comply may result in the issue being closed without discussion, and repeated violations may lead to restrict account from further participation.**![image](https://github.com/user-attachments/assets/a2439bbe-a3e5-4038-9263-a17829382d5b) when this is enabled.

**Comment by namcancode** [comment]
same

**Comment by Dark976** [comment]
Thanks for the reply. I am not sure how to do that. I am using a precompiled ipa which does not seam to have youtubex if that is another tweak.

**Comment by Lilyp3892** [comment]
Is there any eta on when this will get fixed?

**Comment by Dark976** [comment]
That is what i am curious about. It is so annoying to use it like that. You can not comment on anything since no video is showing the relevant desc and comments. Such a deal breaker.

**Comment by dayanch96** [comment]
Completed here: https://github.com/dayanch96/YTLite/releases/tag/v5.1

**Comment by dayanch96** [comment]
@Dark976 @Lilyp3892

**Comment by Dark976** [comment]
Thank you 🙏

**Comment by Lilyp3892** [comment]
Yes thank you!
