### ISSUE TITLE
“Hide shorts” does not hide shorts

### ISSUE THREAD

**Issue by GainingAccess** [dayanch96/YTLite#23]
Device Info:
iOS 16.5.1(c)
Device Model: iPhone 11
Sideloading Tool: Signulous
Version: 2.3

Enabling “Hide Shorts” does not remove shorts
![IMG_3216](https://github.com/dayanch96/YTLite/assets/110878258/2107b472-c4d6-4151-bfb1-1a79e1c3a29c)
![IMG_3218](https://github.com/dayanch96/YTLite/assets/110878258/169b2aee-97d7-479f-8b50-30248ca7ad0d)

How to reproduce issue:
1. Enable “Hide Shorts”
2. Restart the app
3. Shorts are still in the homepage

**Comment by dayanch96** [comment]
I dont have this kind of shorts. which region are you using app from?

**Comment by GainingAccess** [comment]
I am in the United States.

**Comment by GainingAccess** [comment]
Nevermind, I am no longer experiencing the issue, I don’t know what happened but its gone now. I’ll let you know if it comes back.

**Comment by gavyncaldwell** [comment]
I currently have this issue.
