### ISSUE TITLE
Ads block not working well on Short tab

### ISSUE THREAD

**Issue by Mikasa-san** [dayanch96/YTLite#231]
### Describe the bug

```yaml
I noticed that while scrolling through the Shorts tab on YouTube, I come across videos that play ads with descriptions that are completely different from what the videos actually show.
```

### Steps to reproduce

```yaml
1. Go to Short Tab
2. Keep scrolling until you find ad
```

### Post Requisites

- [X] #232
- [X] Verified the relevance of the project and the version you are using.
- [X] Provided a detailed description of the problem and have filled in all required fields.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.
- [X] By submitting this issue, **I confirm that I have filled in all the necessary fields and complied with the guidelines. Failure to comply may result in the issue being closed without discussion, and repeated violations may lead to restrict account from further participation.**

**Comment by dayanch96** [comment]
#227 please be careful next time when you select Post Requisites because its not for fun there

**Comment by Dark976** [comment]
Hi. Since the issue is closed, in which version we will see the fix ?

**Comment by dayanch96** [comment]
> Hi. Since the issue is closed, in which version we will see the fix ?

hopefully in 5.1b3 and public 5.1

**Comment by Dark976** [comment]
> > Hi. Since the issue is closed, in which version we will see the fix ?
> 
> 
> 
> hopefully in 5.1b3 and public 5.1

Do you have a planned release date for public 5.1 ?
