### ISSUE TITLE
Youtube Premium Purchase

### ISSUE THREAD

**Issue by MaciejJezierski** [dayanch96/YTLite#233]
### Describe the bug

```yaml
While checking youtube premium purchase tab I see values in PHP (Philipines) 
1. Is it bug or feature?
2. It is still cheaper then my country, is it safe to buy through app? 
3. Is it possible to change the region from Philippines or can you make it possible? 

PS. I am pretty sure its app related, I am sideloading it with my paid cert from asia though (I am not sure its relevant)
```

### Steps to reproduce

```yaml
Sideload and its there :)
```

### Post Requisites

- [X] I have checked that a similar issue has not been reported before.
- [X] Verified the relevance of the project and the version you are using.
- [X] Provided a detailed description of the problem and have filled in all required fields.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.
- [X] By submitting this issue, **I confirm that I have filled in all the necessary fields and complied with the guidelines. Failure to comply may result in the issue being closed without discussion, and repeated violations may lead to restrict account from further participation.**

**Comment by dayanch96** [comment]
1. Sideloaded app not connected to App Store - you cant buy anything from AppStore on sideloaded app
2. Not related to tweak, can be related to the person who decrypted & based on your IP
