### ISSUE TITLE
The Language changes automatically 

### ISSUE THREAD

**Issue by Inferno-hash** [dayanch96/YTLite#234]
### Describe the bug

```yaml
It’s been happening for quite a while and i finally decided to open an issue about it. Whenever I play a video with multiple languages, the app automatically selects any non-english language and i have to manually change it to english. I’ve tried tweaking the language setting in the yt plus menu but it didn’t fix it.
```

### Steps to reproduce

```yaml
1. Play a video with multiple languages(audio) availabe
```

### Post Requisites

- [X] I have checked that a similar issue has not been reported before.
- [X] Verified the relevance of the project and the version you are using.
- [X] Provided a detailed description of the problem and have filled in all required fields.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.
- [X] By submitting this issue, **I confirm that I have filled in all the necessary fields and complied with the guidelines. Failure to comply may result in the issue being closed without discussion, and repeated violations may lead to restrict account from further participation.**

**Comment by dayanch96** [comment]
Have you tried selecting preferred audio track in player settings? I need more info

**Comment by dayanch96** [comment]
Huh? Linus Tech Tips has only english audio-track

**Comment by Inferno-hash** [comment]
> Huh? Linus Tech Tips has only english audio-track

Im sorry I didn’t mention it but I meant the older videos (please look at the videos released 7-8 months prior).
I could send you the video links on your telegram if needed.

**Comment by Inferno-hash** [comment]
Devices:- iPad pro 3rd gen & iPhone 13
Ios version:- 18.0.1 on both
Youtube version :- currently 19.35.3 ( but ive tried multiple versions and the issue persists)
Yt plus version :- 5.0.2 +YOUPiP ,YTUhd and RYD

**Comment by dayanch96** [comment]
i heard its YTUHD issue but have to check. what's your YouTube and System language? English?

**Comment by Inferno-hash** [comment]
> i heard its YTUHD issue but have to check. what's your YouTube and System language? English?

Yes(English US)

**Comment by dayanch96** [comment]
None of tried by me videos had this issue. Make sure that there no conflicting tweaks
