### ISSUE TITLE
App crashes when activating “Display segments in the feed” in SponsorBlock

### ISSUE THREAD

**Issue by LPR6** [dayanch96/YTLite#235]
### Describe the bug

```yaml
Youtube Plus crashes when I activate “Display segments in the feed” in the SponsorBlock settings menu. This only occurs when playback in feeds is on.
```

### Steps to reproduce

```yaml
1. Settings->General->turn on Playback in feeds
2. Settings->Youtube Plus->SponsorBlock->turn on Display segments in the feed
3. App crashes when playback starts in the feed, without opening any video.
```

### Post Requisites

- [X] I have checked that a similar issue has not been reported before.
- [X] Verified the relevance of the project and the version you are using.
- [X] Provided a detailed description of the problem and have filled in all required fields.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.
- [X] By submitting this issue, **I confirm that I have filled in all the necessary fields and complied with the guidelines. Failure to comply may result in the issue being closed without discussion, and repeated violations may lead to restrict account from further participation.**

**Comment by dayanch96** [comment]
#183
