### ISSUE TITLE
App crashes when downloading mp3

### ISSUE THREAD

**Issue by ros0fg** [dayanch96/YTLite#236]
### Describe the bug

```yaml
App crashes when downloading mp3
```

### Steps to reproduce

```yaml
Tap download 
Choose audio
It’ll crash
```

### Post Requisites

- [X] I have checked that a similar issue has not been reported before.
- [X] Verified the relevance of the project and the version you are using.
- [X] Provided a detailed description of the problem and have filled in all required fields.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.
- [X] By submitting this issue, **I confirm that I have filled in all the necessary fields and complied with the guidelines. Failure to comply may result in the issue being closed without discussion, and repeated violations may lead to restrict account from further participation.**

**Comment by ros0fg** [comment]
Not only mp3 but also videos

**Comment by dayanch96** [comment]
don't use YT 19.42+ until 5.1

**Comment by dayanch96** [comment]
https://github.com/dayanch96/YTLite/releases/tag/v5.1
