### ISSUE TITLE
Ads in shorts get played instead of some videos

### ISSUE THREAD

**Issue by MrZomka** [dayanch96/YTLite#239]
### Describe the bug

```yaml
It’s a bit hard to explain, but essentially, when you’re watching shorts, you might get an ad that will sort of not be a separate short and just play instead of a different short but that different short will replacing the next and so on and so on. 

Here’s a screen recording of this issue: https://files.catbox.moe/39pvo2.mp4

It occurred on two different devices. Both are on 17.0 and have YTLite (5.0.2) with a few other tweaks installed through Bootstrap and YouTube 19.39.1.
```

### Steps to reproduce

```yaml
1. Start watching shorts
2. Scroll
3. You’ll get an ad instead of a regular short and your queue will be messed up
```

### Post Requisites

- [X] I have checked that a similar issue has not been reported before.
- [X] Verified the relevance of the project and the version you are using.
- [X] Provided a detailed description of the problem and have filled in all required fields.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.
- [X] By submitting this issue, **I confirm that I have filled in all the necessary fields and complied with the guidelines. Failure to comply may result in the issue being closed without discussion, and repeated violations may lead to restrict account from further participation.**

**Comment by dayanch96** [comment]
#227
