### ISSUE TITLE
Sign in issue

### ISSUE THREAD

**Issue by 3daguysman** [dayanch96/YTLite#24]
Can you add a sign in fix which was added on uyouplus i keep getting logged out if i close the app im using signulous to sign the app

**Comment by dayanch96** [comment]
problem might be in your signing method. fix literally same.

**Comment by LenardValdez** [comment]
I found a fix for this for signulous. Go to uuid registrations(also owned by signulous) then get your p12 files and provision, it may ask for your uuid for purchase verification even if you purchased from signulous. Go download e-sign import all your certs to e-sign, sign the ipa with the "apple distribution" cert and then you're golden

**Comment by dayanch96** [comment]
or just import embedded.mobileprovision file into apps directory
