### ISSUE TITLE
[v5.1] Visual Bug: Translucent tab bar + legacy iPhone miniplayer

### ISSUE THREAD

**Issue by Prakyy** [dayanch96/YTLite#250]
### Describe the bug

```yaml
https://imgur.com/a/q6bR0ls

Please refer the screenshot

There is a gap between the tab bar and miniplayer but only if the tab bar is set to translucent.
```

### Steps to reproduce

```yaml
1. Turn on translucent tab bar
2. Turn on legacy iPhone mini-player design
3. Open a video and swipe down.
```

### Post Requisites

- [X] I have checked that a similar issue has not been reported before.
- [X] Verified the relevance of the project and the version you are using.
- [X] Provided a detailed description of the problem and have filled in all required fields.
- [X] I did not answer truthfully to **ALL** the above checkboxes.
- [X] By submitting this issue, **I confirm that I have filled in all the necessary fields and complied with the guidelines. Failure to comply may result in the issue being closed without discussion, and repeated violations may lead to restrict account from further participation.**

**Comment by dayanch96** [comment]
its not bug, since translucent tab bar from new interface and old miniplayer from old, it may look weird with solid black miniplayer. and its not actually gap but translucent tab bar's translucent borders, 2px or so
