### ISSUE TITLE
Little gap between the mini player and symbolbar

### ISSUE THREAD

**Issue by Ketarmin** [dayanch96/YTLite#254]
### Describe the bug

```yaml
I noticed that with the latest and greatest update the is a little gap between the mini player and the symbobar 

I unfortunately can’t findout if it’s coursed by any new implemented setting or…
```

### Steps to reproduce

```yaml
Drag the player into the mini player and you will the a thin gap between the mini player and the symbolbar
```

### Post Requisites

- [X] I have checked that a similar issue has not been reported before.
- [X] Verified the relevance of the project and the version you are using.
- [X] Provided a detailed description of the problem and have filled in all required fields.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.
- [X] By submitting this issue, **I confirm that I have filled in all the necessary fields and complied with the guidelines. Failure to comply may result in the issue being closed without discussion, and repeated violations may lead to restrict account from further participation.**

**Comment by Ketarmin** [comment]
https://github.com/user-attachments/assets/79a9f4dd-7ca7-4537-a646-c009e9416580

**Comment by dayanch96** [comment]
Enabling `I have checked that a similar issue has not been reported before.` without actually checking may considered as violation and you can be restricted from accessing repo

#250

**Comment by Ketarmin** [comment]
Ups sorry, shame on me
