### ISSUE TITLE
Context Menu: Reordering and hiding elements

### ISSUE THREAD

**Issue by Infinitay** [dayanch96/YTLite#257]
### Describe the feature request

_Originally I was going to piggy-back off #255 but I think this deserves it's own request_

I would like to request the following changes to the existing context menu options within the Interface settings on YTLite:

- The ability to re-order the various context menu options
- The ability to hide/show the various context menu options

Essentially, I am requesting YTLite's context menu changes found within the Interface settings to be refactored to a setting style similar to that of the Tab bar where you can de(activate) and re-order options.

Thank you.

---

### Post Requisites

- [X] I have checked that a similar feature request has not been reported before.
- [X] Verified the relevance of the project and the version you are using.
- [X] Provided a detailed description of the request and have filled in all required fields.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.
- [X] By submitting this request, **I confirm that I have filled in all the necessary fields and complied with the guidelines. Failure to comply may result in the request being closed without discussion, and repeated violations may lead to restrict account from further participation.**

**Comment by dayanch96** [comment]
Hey,

While it’s a cool and creative idea, I don’t think it’s particularly useful in practice. Implementing it would require rewriting a significant amount of code and would likely confuse regular users. For these reasons, I don’t plan to work on it - sorry about that.

That said, I really appreciate that you took the time to properly follow the guidelines for feature requests and for providing such a detailed description. Thank you!

**Comment by Infinitay** [comment]
Understandable, thank you for the reply.
