### ISSUE TITLE
Old dark mode

### ISSUE THREAD

**Issue by naoto0826g** [dayanch96/YTLite#260]
### Describe the feature request

```yaml
Is it possible to add a gray theme?
YTPlus_19.47.7_5.1
```

### Post Requisites

- [X] I have checked that a similar feature request has not been reported before.
- [X] Verified the relevance of the project and the version you are using.
- [X] Provided a detailed description of the request and have filled in all required fields.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.
- [X] By submitting this request, **I confirm that I have filled in all the necessary fields and complied with the guidelines. Failure to comply may result in the request being closed without discussion, and repeated violations may lead to restrict account from further participation.**

**Comment by dayanch96** [comment]
sorry, not planned for now
