### ISSUE TITLE
Community Posts do not zoom out when tapped

### ISSUE THREAD

**Issue by HorsePuncherDraugr** [dayanch96/YTLite#261]
### Describe the bug

```yaml
The ability to tap a community post image to zoom it out and see the full image does not work properly.
```

### Steps to reproduce

```yaml
Go to any channels community post section or any community post in feed.

If post is a large image it will be zoomed it.

Tap the image. It will likely do nothing but it is supposed to resize the image so that it is fully visible.
```

### Post Requisites

- [X] I have checked that a similar issue has not been reported before.
- [X] Verified the relevance of the project and the version you are using.
- [X] Provided a detailed description of the problem and have filled in all required fields.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.
- [X] By submitting this issue, **I confirm that I have filled in all the necessary fields and complied with the guidelines. Failure to comply may result in the issue being closed without discussion, and repeated violations may lead to restrict account from further participation.**

**Comment by dayanch96** [comment]
Enabling `I have checked that a similar issue has not been reported before` without actually checking may considered violation and you can be restricted from accessing repo

https://github.com/dayanch96/YTLite/issues/195

In 5.1 I added image viewer. Long tap on image and select ‘Show this image’
