### ISSUE TITLE
Any way to get Playback speed to work per channel based

### ISSUE THREAD

**Issue by Blockr22** [dayanch96/YTLite#262]
### Describe the feature request

```yaml
Playback speed settings be saved & remembered per channel instead of being same for every channel.

And can u plz add uYouQuality tweak, it’s very easy to change quality by using that tweak.
Using latest 5.1 version
```

### Post Requisites

- [X] I have checked that a similar feature request has not been reported before.
- [X] Verified the relevance of the project and the version you are using.
- [X] Provided a detailed description of the request and have filled in all required fields.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.
- [X] By submitting this request, **I confirm that I have filled in all the necessary fields and complied with the guidelines. Failure to comply may result in the request being closed without discussion, and repeated violations may lead to restrict account from further participation.**

**Comment by dayanch96** [comment]
maybe? but i’m not interested in such feature. sorry

**Comment by Blockr22** [comment]
That’s kk, thnx for the hard work
