### ISSUE TITLE
Add fullscreen to the right

### ISSUE THREAD

**Issue by rafaeldamasceno** [dayanch96/YTLite#263]
### Describe the feature request

```yaml
By default, the button and swipe for fullscreen make it go to the left. It would be nice to have a way to be able to make fullscreen go to the right when you have rotation lock enabled.
```

### Post Requisites

- [X] I have checked that a similar feature request has not been reported before.
- [X] Verified the relevance of the project and the version you are using.
- [X] Provided a detailed description of the request and have filled in all required fields.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.
- [X] By submitting this request, **I confirm that I have filled in all the necessary fields and complied with the guidelines. Failure to comply may result in the request being closed without discussion, and repeated violations may lead to restrict account from further participation.**

**Comment by dayanch96** [comment]
Enabling `I have checked that a similar issue has not been reported before` without actually checking may considered violation and you can be restricted from accessing repo

https://github.com/dayanch96/YTLite/issues/191

**Comment by rafaeldamasceno** [comment]
I’ve searched it and checked in like 3 different ways. That issue is worded in a pretty convoluted way. In any case, my bad.
