### ISSUE TITLE
Add quality indicator and switcher to the player overlay

### ISSUE THREAD

**Issue by rafaeldamasceno** [dayanch96/YTLite#264]
### Describe the feature request

```yaml
Add the option to have a button/indicator that displays current video quality in the overlay. When tapped, the indicator should open the video quality options.
```

### Post Requisites

- [X] I have checked that a similar feature request has not been reported before.
- [X] Verified the relevance of the project and the version you are using.
- [X] Provided a detailed description of the request and have filled in all required fields.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.
- [X] By submitting this request, **I confirm that I have filled in all the necessary fields and complied with the guidelines. Failure to comply may result in the request being closed without discussion, and repeated violations may lead to restrict account from further participation.**

**Comment by vikasbhatia** [comment]
Hi, was this added? I was looking for this as well but could not find it in the options anywhere. This issue exists but is closed, so I wasn't sure whether I should open another one asking for it.

Thanks

**Comment by rafaeldamasceno** [comment]
@vikasbhatia I closed it becaue of #205. I just built my own IPA with YouQuality.

**Comment by vikasbhatia** [comment]
@rafaeldamasceno Ah got it. Could you please point me in the right direction on how to do that? I use Feather.

As far as I know you can select a `.deb` to inject into an IPA at the time of installing, but I don't see anything like that in the [YouQuality repo.](https://github.com/PoomSmart/YouQuality?tab=releases)

**Comment by rafaeldamasceno** [comment]
I tried with some .deb available if you search for the tweak names, but it wasn’t working well, so I just forked the repo and changed the workflow to include it when building: https://github.com/rafaeldamasceno/YTLite/blob/fc9e08ec629ac2db5aaf45b8b3f642a48059263a/.github/workflows/ytp_tweaks.yml#L130

**Comment by vikasbhatia** [comment]
That's neat. Thank you very much!
