### ISSUE TITLE
Add to AltStore

### ISSUE THREAD

**Issue by Amazon90** [dayanch96/YTLite#266]
### Describe the feature request

```yaml
When I added the following link to the AltStore source, an error occurred.

https://raw.githubusercontent.com/dayanch96/YTLite/refs/heads/main/Resources/depiction.json

The data couldn't be read
because it is missing.
No value associated with key
CodingKeys (stringValue: "name",
intValue: nil) ("name").
```

### Post Requisites

- [X] I have checked that a similar feature request has not been reported before.
- [X] Verified the relevance of the project and the version you are using.
- [X] Provided a detailed description of the request and have filled in all required fields.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.
- [X] By submitting this request, **I confirm that I have filled in all the necessary fields and complied with the guidelines. Failure to comply may result in the request being closed without discussion, and repeated violations may lead to restrict account from further participation.**

**Comment by dayanch96** [comment]
It has nothing to do with AltStore. It’s Sileo depiction
