### ISSUE TITLE
Github Action Fails at IPA Validation regardless of site used

### ISSUE THREAD

**Issue by rachitest** [dayanch96/YTLite#272]
### Describe the bug

```yaml
GitHub Actions workflow build keeps failing at the "Validate IPA URL" step regardless of where the link originates. Have tried building with links from litterbox, catbox, onedrive, and filebin.
```

### Steps to reproduce

```yaml
1. Enable github actions
2. Run "Create Youtube Plus App" workflow
3. Provide link to decrypted IPA
4. Watch build fail
```

### Post Requisites

- [X] I have checked that a similar issue has not been reported before.
- [X] Verified the relevance of the project and the version you are using.
- [X] Provided a detailed description of the problem and have filled in all required fields.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.
- [X] By submitting this issue, **I confirm that I have filled in all the necessary fields and complied with the guidelines. Failure to comply may result in the issue being closed without discussion, and repeated violations may lead to restrict account from further participation.**

**Comment by LandonFrost** [comment]
Happening to me too. Not sure what's going on.

**Comment by dayanch96** [comment]
one moment. let me re-check

**Comment by dayanch96** [comment]
My bad. Should work properly now

**Comment by Yunogamer** [comment]
still doesnt work

**Comment by dayanch96** [comment]
Which file hosting servise you’re using?

**Comment by dayanch96** [comment]
Ok. Now fixed

**Comment by 75Y** [comment]
yeah it now works

**Comment by Blockr22** [comment]
I m still having this issue. I am using file.io

**Comment by dayanch96** [comment]
> I m still having this issue. I am using file.io

How if you don't have any unsuccessful workflows?

**Comment by Blockr22** [comment]
Thnx that worked but i am not sure what changed, i always used file.io till now & it worked just fine. But thnx again. It worked with other examples u mentioned

**Comment by dayanch96** [comment]
> Thnx that worked but i am not sure what changed, i always used file.io till now & it worked just fine. But thnx again. It worked with other examples u mentioned 

that's because i download a small part to check file type now, and service will consider file as downloaded, and, probably, removes it
