### ISSUE TITLE
Buffering & this bug

### ISSUE THREAD

**Issue by Blockr22** [dayanch96/YTLite#274]
### Describe the bug

```yaml
Video’s are buffering and UI sometimes gets stuck with loading wheel but video keeps playing
```

### Steps to reproduce

```yaml
Just play anything
```

### Post Requisites

- [X] I have checked that a similar issue has not been reported before.
- [X] Verified the relevance of the project and the version you are using.
- [X] Provided a detailed description of the problem and have filled in all required fields.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.
- [X] By submitting this issue, **I confirm that I have filled in all the necessary fields and complied with the guidelines. Failure to comply may result in the issue being closed without discussion, and repeated violations may lead to restrict account from further participation.**

**Comment by dayanch96** [comment]
try without ytuhd

**Comment by Blockr22** [comment]
Do u mean disable VP9, if so i tried that & now it’s not buffering. But the weird thing is 4k still works. I always thought 4k don’t work without vp9 enable. I am using iPhone 15pro max if that makes any difference. Thnx

**Comment by dayanch96** [comment]
All App Store apps, including sideloaded ones, require a special entitlement to use the VP9 codec, and only Apple can grant this entitlement. In Google’s case, Apple has granted this to their App Store account (team ID).

When you decrypt and resign an app using your own account, the app loses this special entitlement for VP9 support.

YTUHD relies on hardware acceleration. If your device isn’t powerful enough to download media, convert it in real-time to a supported format, and play it at the same time, you may and probably will experience buffering and overheating issues.

However, this doesn’t apply to the iPhone 15 PRO and 16 PRO series, which natively support the AV1 codec without requiring any special entitlements.

**Comment by Blockr22** [comment]
Yeah, after a while now it only play upto 1080p. But since i am using 15pro max. Why is there buffering & that bug where video is playing but still seeing buffering screen.
![IMG_3364](https://github.com/user-attachments/assets/133d007f-6fcf-4413-a7e9-2e5368ef86b7)

**Comment by dayanch96** [comment]
because audio and video separated.

while it can play audio, it can’t convert avc (mp4) video as vp9 (webp) to regular av (mp4) to play it. its only my guess, i never analyzed it and don’t want to

**Comment by Blockr22** [comment]
Kk, thnx. After enabling vp9 again . Its working without buffering. Thnx

**Comment by dayanch96** [comment]
bruh, your device don’t use VP9 at all. its up to you, but enabling that will overheat your device in few minutes. letting you know

**Comment by Blockr22** [comment]
Ohh, so even if i disable vp9. I should have 4k resolution in all videos ?

**Comment by dayanch96** [comment]
in 90% if not in all. google uses it by default as far as i know

**Comment by EagleEye9219** [comment]
Do you mean, with vp9 disabled I should get 4K videos when streaming ?

I can’t see that resolution when watching but when I want to download it’s there
