### ISSUE TITLE
Return YouTube Dislike?

### ISSUE THREAD

**Issue by PianoMan7** [dayanch96/YTLite#277]
### Describe the bug

```yaml
Sorry, this might be a really dumb question, but for the life of me I cannot find the “return YouTube dislike” option in the settings. I’m on version 19.47.7.
```

### Steps to reproduce

```yaml
N/A
```

### Post Requisites

- [X] I have checked that a similar issue has not been reported before.
- [X] Verified the relevance of the project and the version you are using.
- [X] Provided a detailed description of the problem and have filled in all required fields.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.
- [X] By submitting this issue, **I confirm that I have filled in all the necessary fields and complied with the guidelines. Failure to comply may result in the issue being closed without discussion, and repeated violations may lead to restrict account from further participation.**

**Comment by dayanch96** [comment]
Make sure you’re using latest RYD
![image](https://github.com/user-attachments/assets/8c5fce13-7bce-4dd9-863d-47db0a405f80)
