### ISSUE TITLE
Feature request: disable cc by default

### ISSUE THREAD

**Issue by Macleykun** [dayanch96/YTLite#28]
Hello!
I wanted to suggest if it's possible to toggle automatic subtitles/CC off, as in some video's it is turned on by default (yes on desktop i unchecked both options so it won't appear there, but it still does on my iDevice).

**Comment by dayanch96** [comment]
I’ll take a look

**Comment by Macleykun** [comment]
Thank you so much! ☺️ take your time!Op 26 aug 2023 om 11:09 heeft Dan ***@***.***> het volgende geschreven:﻿
I’ll take a look

**Comment by Macleykun** [comment]
I'm closing this one as i don't seem to have this issue anymore.
Thank you so much for your work into ytlite, it's extremely helpful and i use it alot!

**Comment by dayanch96** [comment]
If you still have this issue, this option added in latest release https://github.com/dayanch96/YTLite/releases/tag/v2.5

**Comment by Macleykun** [comment]
> If you still have this issue, this option added in latest release https://github.com/dayanch96/YTLite/releases/tag/v2.5

Omg! thank you so much! I didn't have it as much as i had in the past (mainly with mr beast video's which is odd). But thank you for working on this i really appricate it and will update to this once ytliteplus is updated!

Have a great weekend! <3
