### ISSUE TITLE
Show current image, Copy current image option wont animate the gif image

### ISSUE THREAD

**Issue by dora727** [dayanch96/YTLite#280]
### Describe the bug

```yaml
As the title said, Using “Show current image” or “Copy current image” option on community tab wont animate the GIF image. Save current image option had no problem
```

### Steps to reproduce

```yaml
http://youtube.com/post/UgkxLGXv55vw0UeCnb8ip-p-O3pPnPtc111U?si=uiOzH6-c4mnaDG7q
(the post that i saw)
```

### Post Requisites

- [X] I have checked that a similar issue has not been reported before.
- [X] Verified the relevance of the project and the version you are using.
- [X] Provided a detailed description of the problem and have filled in all required fields.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.
- [X] By submitting this issue, **I confirm that I have filled in all the necessary fields and complied with the guidelines. Failure to comply may result in the issue being closed without discussion, and repeated violations may lead to restrict account from further participation.**

**Comment by dora727** [comment]
https://github.com/user-attachments/assets/99aa192d-25d0-44da-8887-cafd3041af97

**Comment by dayanch96** [comment]
hey. yes, i don’t want to include webp only for 2-3 gifs - sorry. you can use pfpviewer for that if you wish
