### ISSUE TITLE
Video comments

### ISSUE THREAD

**Issue by hshdhdhfbbdh** [dayanch96/YTLite#281]
### Describe the bug

```yaml
YouTube crashes when opening the comments of a video when a user pops up in the comment bar.
```

### Steps to reproduce

```yaml
1. Open YouTube OLED
2. Play a video
3. Go to comments
4. Wait for a user’s comment to pop up
5. Tap on comments then crash
```

### Post Requisites

- [X] I have checked that a similar issue has not been reported before.
- [X] Verified the relevance of the project and the version you are using.
- [X] Provided a detailed description of the problem and have filled in all required fields.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.
- [X] By submitting this issue, **I confirm that I have filled in all the necessary fields and complied with the guidelines. Failure to comply may result in the issue being closed without discussion, and repeated violations may lead to restrict account from further participation.**

**Comment by dayanch96** [comment]
Not sure which mod you’re using but try the one i post in telegram
