### ISSUE TITLE
Open links in youtube app rather than browser

### ISSUE THREAD

**Issue by Keysz** [dayanch96/YTLite#283]
### Describe the bug

```yaml
When I click on a shared YT link, it takes me to a default browser (i.e. Safari). Is there a way where YT links can redirect directly to the app instead?

Apologies if there is a very basic fix. I'm just not seeing it
```

### Steps to reproduce

```yaml
Example. 

1. www.youtube.com
2. link opens in Safari
3. No option to redirect to Youtube app
```

### Post Requisites

- [X] I have checked that a similar issue has not been reported before.
- [X] Verified the relevance of the project and the version you are using.
- [X] Provided a detailed description of the problem and have filled in all required fields.
- [X] I did not answer truthfully to **ALL** the above checkboxes.
- [X] By submitting this issue, **I confirm that I have filled in all the necessary fields and complied with the guidelines. Failure to comply may result in the issue being closed without discussion, and repeated violations may lead to restrict account from further participation.**

**Comment by dayanch96** [comment]
Not tweak related issue. Sideloading issue. If you’re building app via Github actions, enable Safari extension after installing the app
