### ISSUE TITLE
Age restricted videos don't load

### ISSUE THREAD

**Issue by hiddensea** [dayanch96/YTLite#32]

**Comment by hiddensea** [comment]
Sharing options don’t load but try https://youtu.be/hIMRrIUQvgE?si=vCOH0R6Iq4k3Fpa9On 29 Aug 2023, at 15:20, Dan ***@***.***> wrote:﻿
Can I have an example link?

**Comment by dayanch96** [comment]
have you enabled mini player in player options? everything works fine on my side

**Comment by dayanch96** [comment]
Given your mentioned issue, it depends on the installation method and not age restriction issue
