### ISSUE TITLE
How to force VP9 codec for all resolutions?

### ISSUE THREAD

**Issue by haomuch** [dayanch96/YTLite#35]
I have enabled the VP9 codec in settings but from the stats VP9 codec is used only for 2k/4k resolution. I know that the difference of video size between VP9 and AVC under 2k res is not as significant as that of 2k/4k res. But I still want to force VP9 codec for all res as it is on the official Youtube app and uYouPlus 18.14.1-3.0. Could anyone tell me how to do that or we need to wait for a future release?

**Comment by dayanch96** [comment]
guess you’re using all-in-one ipa apps. ytlite doesnt contain vp9 codec enabling feature
