### ISSUE TITLE
Installation doubt

### ISSUE THREAD

**Issue by michael1900** [dayanch96/YTLite#40]
Before install this, we need to uninstall original youtube? 
Same question for music version.

Thanks

**Comment by dayanch96** [comment]
Depends on how you’re trying to install it

**Comment by michael1900** [comment]
> Depends on how you’re trying to install it

Simply with appdb.

**Comment by dayanch96** [comment]
i mean, if you have paid developer certificate and you’re not changing apps bundleid then you’ll have to remove youtube installed from appstore before installation, otherwise just install it and it will appear on your home screen as another application
