### ISSUE TITLE
No pages/videos load

### ISSUE THREAD

**Issue by Landxhent** [dayanch96/YTLite#45]
16.45.4 ios 14.1 taurine YTLITE 2.5
After installation of YTLITE, on main page/library/explore I have continuous activity indicator spinning, like when you spoof yt app version

Only shorts are working 

All options in YTLITE are disabled, advanced mode off. Tried all of it on as well 

Have all tweaks disabled except of it - same.

Without YTLITE - everything is fine (well, except videos do not appear on main page after some scrolling, lol)

Any solution?

**Comment by dayanch96** [comment]
how to reproduce?
