### ISSUE TITLE
Can't build latest version

### ISSUE THREAD

**Issue by Balackburn** [dayanch96/YTLite#62]
Since 2.6.2 `make clean package` result in the followings errors : 

==> Compiling YTLite.x (arm64)…
YTLite.x:576:62: error: property 'parentViewController' not found on object of type 'YTPlaybackControllerUIWrapper *'
    if (kPinchToFullscreenShorts && [self.playerViewDelegate.parentViewController isKindOfClass:NSClassFromString(@"YTShortsPlayerViewController")]) {
                                                             ^
YTLite.x:577:112: error: property 'parentViewController' not found on object of type 'YTPlaybackControllerUIWrapper *'
        YTShortsPlayerViewController *shortsPlayerVC = (YTShortsPlayerViewController *)self.playerViewDelegate.parentViewController;
                                                                                                               ^
YTLite.x:601:53: error: property 'parentViewController' not found on object of type 'YTPlaybackControllerUIWrapper *'
    if (kShortsOnlyMode && [self.playerViewDelegate.parentViewController isKindOfClass:NSClassFromString(@"YTShortsPlayerViewController")]) {
                                                    ^
YTLite.x:625:112: error: property 'parentViewController' not found on object of type 'YTPlaybackControllerUIWrapper *'
        YTShortsPlayerViewController *shortsPlayerVC = (YTShortsPlayerViewController *)self.playerViewDelegate.parentViewController;
                                                                                                               ^
4 errors generated.

**Comment by Balackburn** [comment]
I use latest YouTubeHeader by PoomSmart

**Comment by Balackburn** [comment]
I didn't had it but adding it doesn't fix the issue, do I need to add it below a specific @interface or anywhere should work?

**Comment by dayanch96** [comment]
![image](https://github.com/dayanch96/YTLite/assets/38832025/ebb00865-b3cc-410b-9d55-94f819bfbdc3)

**Comment by Balackburn** [comment]
I did had it already, I cloned your repostory I am on the latest commit and didn't the line because I added a space at the start in search.

**Comment by dayanch96** [comment]
are you trying to build it as ytlite or ytliteplus?

**Comment by Balackburn** [comment]
I have the problem on YTLitePlus, then tested YTLite and also have the problem
<img width="1511" alt="Capture d’écran 2024-02-22 à 14 09 06" src="https://github.com/dayanch96/YTLite/assets/93828569/f04116cb-4966-492c-b7e3-909dad480a20">

**Comment by dayanch96** [comment]
it is clearly written in terminal what is missing
![image](https://github.com/dayanch96/YTLite/assets/38832025/3b12e2c6-eec7-49af-b6c2-cad41bf7bccf)

**Comment by Balackburn** [comment]
I do have it :

<img width="1396" alt="Capture d’écran 2024-02-22 à 14 22 33" src="https://github.com/dayanch96/YTLite/assets/93828569/37a6e8d3-0575-46b0-b98d-f4fac527a78c">

**Comment by dayanch96** [comment]
you have already included YTPlayerView.h from YouTubeHeader. I wonder why? If you trying to use it, then declare in YTLite.h as `@interface YTPlayerView ()` and not as `@interface YTPlayerView : UIView`

**Comment by dayanch96** [comment]
I recommend reading something like this to understand, why:
https://www.geeksforgeeks.org/interface-in-objective-c/

**Comment by dayanch96** [comment]
but i dont have YTLite/../YouTubeHeader/YTPlayerView.h in YTLite.h

**Comment by Balackburn** [comment]
I didn't edited anything, cloned everything in a new folder

**Comment by Macleykun** [comment]
> I didn't edited anything, cloned everything in a new folder

Did you manage to compile it :) ?

**Comment by Balackburn** [comment]
@Macleykun Look at my fork I did a dirty edit that work

**Comment by Balackburn** [comment]
@Macleykun https://github.com/Balackburn/YTLite

**Comment by dayanch96** [comment]
> @Macleykun Look at my fork I did a temp edit that worked for compiling it

my man just removed whole class hook...😂

**Comment by Balackburn** [comment]
@dayanch96 I know but it’s hella dirty but it work and I don’t use it

**Comment by Balackburn** [comment]
Thank you !
