### ISSUE TITLE
'You' tab - where is it?

### ISSUE THREAD

**Issue by jackhinkle** [dayanch96/YTLite#65]
I like the new You tab. After opening the app a few times after installation, it goes away and stays gone forever, replaced by Library. I've tried the flags discussed [here](https://github.com/MiRO92/uYou-for-YouTube/issues/285) with no luck.

I'm curious as to why this might be happening. If it's knowingly already being blocked by YTLite, then I would very much prefer a toggle to switch between it and the Library tab. If it's not knowingly being blocked by YTLite... well I guess that's something to look into.

Apologies for logging this as an issue, but this repo has discussions disabled.

**Comment by dayanch96** [comment]
Probably issue in enabling YT classic quality and Extra speed options as these options spoofs yt version to correctly display their menus

**Comment by jackhinkle** [comment]
Ah, that's exactly right. I disabled extra speed options, and the You tab returned. I'd consider this issue closed unless you want to make a note about it somewhere in the menus.

**Comment by dayanch96** [comment]
ill figure out tomorrow something

**Comment by dayanch96** [comment]
Done
