### ISSUE TITLE
"Disable snap to chapter" isn't working 

### ISSUE THREAD

**Issue by vitalik2187836** [dayanch96/YTLite#70]
As title says enabling "Disable snap to chapter" option in settings won't have any effect. 
I still able to skip chapters by double press with two fingers on either side of the phone. 
I've tried this on jailbreak version on iPhone 11 pro (YTLite 2.7) and on YTLite Plus 19.08.2_2.7 on iPhone 15 pro.

**Comment by dayanch96** [comment]
How can i test it? any links?

**Comment by vitalik2187836** [comment]
Sure 
https://youtu.be/3P2ijQ3rcm8?si=28tQykivd6XhYgfK

**Comment by dayanch96** [comment]
Не-а, что-то нифига не хочет перепрыгивать на эпизод. Ты точно включил эту опцию?

**Comment by dayanch96** [comment]
> В смысле, а разве перемотка эпизодов одним пальцем бывает? Если так, то можно как-то отключить вообще эту перемотку эпизодов? Я просто двумя пальцами быстро поочередно тапаю и он регистрирует это как двойное нажатие. Бесит безумно.

Еще как. Рандомно, пытаешься перемотать на 15 сек, а оно тебя перекидывает на следующий эпизод.

Хотя, думаю, и двойной тап двумя пальцами можно отменить. Гляну чуть позже

**Comment by vitalik2187836** [comment]
Понял, возможно и на это я натыкался. Но если можно будет отрубить это накорню, то будет вообще божественно :)

**Comment by dayanch96** [comment]
Выполнено в версии 3.0
