### ISSUE TITLE
Hiding shorts create an empty space instead

### ISSUE THREAD

**Issue by Balackburn** [dayanch96/YTLite#71]
The "Hide Shorts videos" option creates an empty space in the Subscription and Explore tabs :
![Capture d’écran   2024-02-28 à 22 06 52](https://github.com/dayanch96/YTLite/assets/93828569/8ff6aff6-bf98-4ab0-8245-2894ce0eda8b)

**Comment by dayanch96** [comment]
known issue. i don't have a solution yet

**Comment by Balackburn** [comment]
@dayanch96 It's fixed in latest YTUnshort update, maybe you could use it or take inspiration to fix this issue.

https://raw.githubusercontent.com/PoomSmart/YTUnShorts/main/Tweak.x

**Comment by dayanch96** [comment]
> @dayanch96 It's fixed in latest YTUnshort update, maybe you could use it or take inspiration to fix this issue.
> 
> https://raw.githubusercontent.com/PoomSmart/YTUnShorts/main/Tweak.x

I thought it was my pull. As you already seen I didn't updated YTLite source code for a while. But I already fixed it yesterday, thanks

**Comment by Balackburn** [comment]
@dayanch96 Perfect

**Comment by dayanch96** [comment]
Fixed
