### ISSUE TITLE
Blank Home Feed: Issue Possibility 

### ISSUE THREAD

**Issue by NetAnarchy** [dayanch96/YTLite#72]
Hi.
When I updated YTLite 2.4 to 2.6 and later (now 2.7), something weird happened.

YouTube Home feed appears as blank, sometimes videos appear, but when I scroll up or down they vanish again.
It’s also weird that it happens to only one Brand account, it doesn’t affect other accounts.

Also I tried few things:
- Restarting iPhone 
- Reinstalling YTLite ipa (using TrollStore)
- **Reinstalling normal YouTube app**
- Turning on/off Incognito 

As it shows as bold text, normal YouTube app worked correctly, but I couldn’t get any information worth about it.

In base of web-information, it’s said it’ll happen to any accounts randomly.

Anyone else facing this problem?
Thx ;)

**Comment by dayanch96** [comment]
have you enabled hide shorts feature?

**Comment by NetAnarchy** [comment]
Thx for the reply :)

No, but I also tested this feature after issue happened.
It still shows blank but exactly Shorts section disappeared (Shorts logo on Home disappeared).

(Image below is when I turned off Hide Shorts feature)

![IMG_0685](https://github.com/dayanch96/YTLite/assets/116675380/89f759e0-ef03-467f-a9a0-48bf179e0e25)

**Comment by dayanch96** [comment]
how can i reproduce it?

**Comment by NetAnarchy** [comment]
Sorry, what did you mean?

**Comment by dayanch96** [comment]
how can i reproduce blank home feed issue?

**Comment by NetAnarchy** [comment]
Sorry. My environment is

Device: iPhone XS (iPhone 11,2)
iOS: 16.6.1
Install Method: TrollStore

is that okay?

**Comment by dayanch96** [comment]
i mean, what should i do to get blank home feed?

**Comment by NetAnarchy** [comment]
It’s all above. I couldn’t notice what the trigger was, and I can’t give useful information anymore, except YTLite individual settings.
I apologize if I misunderstood what you’re saying, I just wanted to share the hint to solve problem for someone😞

**Comment by dayanch96** [comment]
I think it's the same problem as in #71. Closing this issue as duplication.

**Comment by NetAnarchy** [comment]
Thank you so much.

I don’t know why, but in these days this bug doesn’t appear.
