### ISSUE TITLE
Suggestion: Issue template + stale bot

### ISSUE THREAD

**Issue by Macleykun** [dayanch96/YTLite#76]
I noticed a few people doen’t seem to know how to properly file a but report, perhaps it’s an idea to create a template to get the details from the get go (hopefully).
Documentation: https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository

Also issues and prs that gotten stale may be something you want to use aswell if you want to ofcours!
Documentation: https://github.com/marketplace/actions/close-stale-issues

I can also look at this and make a PR but perhaps you like to finetune this yourself.

feel free to immediately close this issue after reading this :)

**Comment by dayanch96** [comment]
Thanks. Having a template is a good idea i think. I'll take a look

**Comment by haomuch** [comment]
How about directly report issues in the app and send the report to the developers?
