### ISSUE TITLE
Quality tweak

### ISSUE THREAD

**Issue by EscapeAltDelete** [dayanch96/YTLite#8]
Would it be possible to add a tweak that automatically applies the highest quality or that let's you choose a quality that automatically gets applied on video's?

**Comment by dayanch96** [comment]
I’ll take a look but no promises

**Comment by dayanch96** [comment]
Done in: https://github.com/dayanch96/YTLite/releases/tag/v2.7

**Comment by EscapeAltDelete** [comment]
Thank you!! ❤️
