### ISSUE TITLE
Auto disable captions no longer seems to work since a few versions ago

### ISSUE THREAD

**Issue by Macleykun** [dayanch96/YTLite#89]
Hello!

I noticed that the captions were appearing again after having set them to be disabled in ytlite(plus).
Do you experience the same on your device when using the latest version of ytlite(plus) on your iDevice?

**Comment by dayanch96** [comment]
Hi! Sorry, I don’t recommend using any mods of my tweak, since I’m not responsible for them and cant help if any problems arise. Use them at your own risk

But I'll check it. Thank you!

**Comment by Macleykun** [comment]
> Hi! Sorry, I don’t recommend using any mods of my tweak, since I’m not responsible for them and cant help if any problems arise. Use them at your own risk
> 
> But I'll check it. Thank you!

Tottaly understand! If it works for you I’ll see if I can fix it somehow myself! Np!

**Comment by Macleykun** [comment]
Yea YTLitePlus_19.08.2_2.7.ipa works well for me, also the higher res from the get go works!

the bad version for me when it started is: YTLitePlus_19.09.3_2.7.ipa . So I’ll close this issue and sit on that version while I thinker a bit with the ytliteplus and the newer YouTube version.

thank you again and I’ll ofcours in the future I’ll check from the bundled source first instead of going to ytlite obviously! Enjoy the weekend!

**Comment by Macleykun** [comment]
for anyone finding this, i tried this on my phone and didn't had this issue, but a mr beast video was playing the voice track from bulgary weirdly enough. I then deleted the app and reinstalled it fresh and both the audiotrack was correct and the subtitles stayed gone! So if things don't seem to work, i definitly would advice people to first do a clean install!
