### ISSUE TITLE
Shorts overlay settings don't apply

### ISSUE THREAD

**Issue by Uwe5000** [dayanch96/YTLite#90]
the player overlay options for Shorts don't apply 
(like disable search, three dots, remix etc.)

**Comment by Uwe5000** [comment]
iOS 16.3 Dopamine
YouTube version 19.10.5

**Comment by dayanch96** [comment]
Just tested and it works. Make sure you’re using YTLite, not mods

**Comment by Uwe5000** [comment]
Doesn't work for me 
iPhone XR

**Comment by Uwe5000** [comment]
I think the problem is, that the options from advanced mode don't apply sometimes

**Comment by Macleykun** [comment]
Something i've noticed with disableling subtitles is that when you install ytlite over an existent one (i do use ytliteplus) that things don't seem to apply properly. But by removing the app and then installing it things seem to work again!

Could you try that aswell? (you may want to back your config up with taking screenshots?)

**Comment by dayanch96** [comment]
from now, everyone who report issues related to ytlite plus will be blocked

**Comment by Uwe5000** [comment]
it's a YTLite issue...
