### ISSUE TITLE
Auto disable captions doesn't work when auto fullscreen is enabled

### ISSUE THREAD

**Issue by Macleykun** [dayanch96/YTLite#92]
Yes i did test with only sideloading ytlite 3.0.1 on yt 19.10.5.

They both work individually, but together auto disable captions doesn't seem to work. Here is the bug in action: https://share.icloud.com/photos/039z3nVIedoTYc9jg8gVtWCHw

I did patch it by using pyzule.

Device info

- iOS/iPadOS version: 17.4
- Device model: 9th gen ipad
- Sideload tool (AltStore, Sideloadly, TrollStore,...): sidestore
- The specific version of YTLitePlus (latest or newest is NOT a version number!): v19.10.5-3.0.1 - YTLitePlus

Steps to reproduce the issue

1. Toggle in ytlite disable auto captions and play video's in fullscreen
2. Play a recent mr beast video and see that captions still appear
3. (to verify the cc toggle does work) disable play video's in fullscreen and relaunch the video and see the captions are gone.

**Comment by dayanch96** [comment]
https://github.com/dayanch96/YTLite/issues/90#issuecomment-2002560925

**Comment by Macleykun** [comment]
I tested this with only ytlite!

**Comment by Macleykun** [comment]
I meant it like, I got a decrypted yt ipa, and patched it with your deb and tested it with a fresh install, I do hope you’ll still be able to see this message, I specifically wanted to go through the trouble bc of that comment!
