### ISSUE TITLE
Auto disable captions doesn't work when auto fullscreen is enabled

### ISSUE THREAD

**Issue by Macleykun** [dayanch96/YTLite#95]
**Yes i did test with only sideloading ytlite 3.0.1 on yt 19.10.5.**

They both work individually, but together auto disable captions doesn't seem to work. Here is the bug in action: https://share.icloud.com/photos/039z3nVIedoTYc9jg8gVtWCHw0

I did patch it by using pyzule.

Device info

- iOS/iPadOS version: 17.4
- Device model: 9th gen ipad
- Sideload tool (AltStore, Sideloadly, TrollStore,...): sidestore

Steps to reproduce the issue

1. Toggle in ytlite disable auto captions and play video's in fullscreen
2. Play a recent mr beast video and see that captions still appear
3. (to verify the cc toggle does work) disable play video's in fullscreen and relaunch the video and see the captions are gone.

I saw in my previous issue that i copied pasted it but didn't remove the incorrect mention, i really wanted to verify it's a ytlite issue and did so by using pyzule and supplying your .deb file and the decrypted yt ipa to create a pure ytlite ipa that i then sideloaded on my idevice by using sidestore and removing the previous yt app, so that all settings were reset to default.

You can also see in the video i supplied that nothign else is loaded aside from ytlite:
![image](https://github.com/dayanch96/YTLite/assets/26381427/1e51027c-02f1-4e8f-a53a-81775b71a8dd)

I do hope you still see this issue

**Comment by dayanch96** [comment]
Hey. Thanks for the report. I'll try to figure out whats the problem

**Comment by Macleykun** [comment]
> Hey. Thanks for the report. I'll try to figure out whats the problem

Thank you so much! There's no rush ofcours!

**Comment by dayanch96** [comment]
Fixed
