### ISSUE TITLE
[ad-block bug] [v3.0.1] Blank Spaces between videos

### ISSUE THREAD

**Issue by shahin365** [dayanch96/YTLite#98]
### Bug:

There is a blank space on the homepage as I open the app, videos start to appear if I scroll down, but there are blank spaces between videos as I scroll down. After a bit of digging, I found out that the ad block was causing this issue by displaying ads as blank spaces which gets so annoying. right now, the only workaround is to disable the ad-blocker by going to Settings > YTLite > General> toggle-off remove ads. (which defeats the purpose of using YTLite). 

A Reddit thread discussing this bug where users are reporting the same problem: https://new.reddit.com/r/sideloaded/comments/1bfh3yg/anyone_else_getting_a_blank_home_page_in_uyou/ 

### Info:

- iOS version: 17.4.1
- Devices: iPhone 12 pro max & iPhone SE 2020
- Sideload tool Sideloadly
- Current YouTube IPA: 19.16.3
- Current YTLite Version: 3.0.1

### Steps to reproduce the issue:

1. open YTLite
2. Scroll

![IMG_7886](https://github.com/YTLitePlus/YTLitePlus/assets/16749755/1d881f2d-5925-485d-bd5e-79fe6dc45a0a)
![IMG_7887](https://github.com/YTLitePlus/YTLitePlus/assets/16749755/e876ca09-0f40-4d55-a3ee-50609a725d0e)
![IMG_7888](https://github.com/YTLitePlus/YTLitePlus/assets/16749755/dfe79ae4-48b4-49dc-82a8-1a7700ae8cdc)

**Comment by dayanch96** [comment]
Same as in #71
